#!/usr/bin/env python3
"""Merge full A2 აღმართი lessons into lesson_data.json. Run: python3 build_a2_lessons.py"""

import json

from config import LESSON_DATA

A2 = {
    "1": {
        "title": "My Georgian Friend",
        "grammar": {
            "en": "Genitive possession review: ანა-ს ოჯახი (Ana's family). Vowel-ending names take +ს, consonant-ending names take +ის. Compound words: და+ძმა → და-ძმა, დედა+მამა → დედ-მამა. Time range: X-იდან Y-ამდე = from X to Y.",
            "ru": "Повторение родительного: ანა-ს ოჯახი. Имена на гласную получают +ს, на согласную +ის. Сложные слова: და-ძმა, დედ-მამა. Интервал времени: X-იდან Y-ამდე = с X до Y.",
            "example_ge": "ორშაბათიდან პარასკევამდე უნივერსიტეტში ვარ.",
            "example_en": "From Monday to Friday I am at the university.",
        },
        "easier_than_russian": "Georgian compounds are very transparent: და-ძმა literally means sister-brother (siblings).",
        "vocab": [
            {"ge": "დეიდა", "en": "aunt (mother's sister)", "ru": "тётя (по матери)", "group": "Family"},
            {"ge": "მამიდა", "en": "aunt (father's sister)", "ru": "тётя (по отцу)", "group": "Family"},
            {"ge": "ბიძა", "en": "uncle", "ru": "дядя", "group": "Family"},
            {"ge": "ბიძაჩემი", "en": "my uncle", "ru": "мой дядя", "group": "Family"},
            {"ge": "დეიდაჩემი", "en": "my aunt", "ru": "моя тётя", "group": "Family"},
            {"ge": "დეიდაშვილი", "en": "cousin (aunt's child)", "ru": "двоюродный брат/сестра", "group": "Family"},
            {"ge": "მამიდაშვილი", "en": "cousin (father's sister's child)", "ru": "двоюродный брат/сестра", "group": "Family"},
            {"ge": "ბიძაშვილი", "en": "cousin (uncle's child)", "ru": "двоюродный брат/сестра", "group": "Family"},
            {"ge": "და-ძმა", "en": "siblings", "ru": "брат и сестра", "group": "Family"},
            {"ge": "დედ-მამა", "en": "parents", "ru": "родители", "group": "Family"},
            {"ge": "ცოლ-ქმარი", "en": "married couple", "ru": "супружеская пара", "group": "Family"},
            {"ge": "ბებია-ბაბუა", "en": "grandparents", "ru": "бабушка и дедушка", "group": "Family"},
            {"ge": "ფაკულტეტი", "en": "faculty / department", "ru": "факультет", "group": "University"},
            {"ge": "ეკონომიკა", "en": "economics", "ru": "экономика", "group": "University"},
            {"ge": "ბიზნესი", "en": "business", "ru": "бизнес", "group": "University"},
            {"ge": "ბინა", "en": "apartment", "ru": "квартира", "group": "Life"},
            {"ge": "სტუმარი", "en": "guest", "ru": "гость", "group": "Life"},
            {"ge": "ცხოვრება", "en": "life", "ru": "жизнь", "group": "Life"},
            {"ge": "ხშირი", "en": "frequent", "ru": "частый", "group": "Life"},
            {"ge": "ხშირად", "en": "often", "ru": "часто", "group": "Life"},
            {"ge": "მარტო", "en": "alone", "ru": "один/одна", "group": "Life"},
            {"ge": "დედისერთა", "en": "only child", "ru": "единственный ребёнок", "group": "Life"},
            {"ge": "საათიდან", "en": "from (o'clock)", "ru": "с (часа)", "group": "Time"},
            {"ge": "საათამდე", "en": "until (o'clock)", "ru": "до (часа)", "group": "Time"},
        ],
    },
    "2": {
        "title": "A Little About Georgia",
        "grammar": {
            "en": "Instrumental case (-ით): means/instrument/material (ავტობუსით by bus, ქვებით with stones). Adjectives from nouns with -იანი: მზე → მზიანი, წვიმა → წვიმიანი.",
            "ru": "Творительный падеж (-ით): средство, инструмент, материал (ავტობუსით, ქვებით). Прилагательные на -იანი: მზე → მზიანი, წვიმა → წვიმიანი.",
            "example_ge": "საქართველო მთიანი და მზიანი ქვეყანაა.",
            "example_en": "Georgia is a mountainous and sunny country.",
        },
        "easier_than_russian": "Adjectives do not change for gender: მზიანი works with any noun.",
        "vocab": [
            {"ge": "კავკასია", "en": "Caucasus", "ru": "Кавказ", "group": "Geography"},
            {"ge": "მთა", "en": "mountain", "ru": "гора", "group": "Geography"},
            {"ge": "მთიანი", "en": "mountainous", "ru": "гористый", "group": "Geography"},
            {"ge": "მთაგორიანი", "en": "hilly", "ru": "холмистый", "group": "Geography"},
            {"ge": "ზღვა", "en": "sea", "ru": "море", "group": "Geography"},
            {"ge": "სანაპირო", "en": "coast / shore", "ru": "побережье", "group": "Geography"},
            {"ge": "მდინარე", "en": "river", "ru": "река", "group": "Geography"},
            {"ge": "ტყე", "en": "forest", "ru": "лес", "group": "Geography"},
            {"ge": "ტბა", "en": "lake", "ru": "озеро", "group": "Geography"},
            {"ge": "სოფელი", "en": "village", "ru": "деревня", "group": "Geography"},
            {"ge": "რაიონი", "en": "district / region", "ru": "район", "group": "Geography"},
            {"ge": "მხარე", "en": "region / side", "ru": "край / регион", "group": "Geography"},
            {"ge": "ჩრდილოეთი", "en": "north", "ru": "север", "group": "Directions"},
            {"ge": "სამხრეთი", "en": "south", "ru": "юг", "group": "Directions"},
            {"ge": "დასავლეთი", "en": "west", "ru": "запад", "group": "Directions"},
            {"ge": "აღმოსავლეთი", "en": "east", "ru": "восток", "group": "Directions"},
            {"ge": "მზე", "en": "sun", "ru": "солнце", "group": "Weather"},
            {"ge": "მზიანი", "en": "sunny", "ru": "солнечный", "group": "Weather"},
            {"ge": "წვიმა", "en": "rain", "ru": "дождь", "group": "Weather"},
            {"ge": "წვიმიანი", "en": "rainy", "ru": "дождливый", "group": "Weather"},
            {"ge": "თოვლი", "en": "snow", "ru": "снег", "group": "Weather"},
            {"ge": "თოვლიანი", "en": "snowy", "ru": "снежный", "group": "Weather"},
            {"ge": "ღრუბელი", "en": "cloud", "ru": "облако", "group": "Weather"},
            {"ge": "ღრუბლიანი", "en": "cloudy", "ru": "облачный", "group": "Weather"},
            {"ge": "ნისლი", "en": "fog", "ru": "туман", "group": "Weather"},
            {"ge": "ნისლიანი", "en": "foggy", "ru": "туманный", "group": "Weather"},
            {"ge": "ქარიანი", "en": "windy", "ru": "ветреный", "group": "Weather"},
            {"ge": "მეზობელი", "en": "neighbor", "ru": "сосед", "group": "People"},
        ],
    },
    "3": {
        "title": "How They Live in Georgia",
        "grammar": {
            "en": "Modifier + noun: adjective always comes before noun (დიდი სახლი). Time expressions: დილით in the morning, საღამოთი in the evening, ღამით at night, X-ჯერ X times.",
            "ru": "Определение + существительное: прилагательное всегда перед существительным (დიდი სახლი). Время: დილით утром, საღამოთი вечером, ღამით ночью, X-ჯერ X раз.",
            "example_ge": "დილით ნათელ ოთახში ვკითხულობ.",
            "example_en": "In the morning I read in a bright room.",
        },
        "easier_than_russian": "No gender agreement on adjectives: დიდი and ნათელი keep one form.",
        "vocab": [
            {"ge": "ნათესავი", "en": "relative", "ru": "родственник", "group": "People"},
            {"ge": "წევრი", "en": "member", "ru": "член", "group": "People"},
            {"ge": "მამიდა", "en": "paternal aunt", "ru": "тётя по отцу", "group": "People"},
            {"ge": "ბიცოლა", "en": "uncle's wife", "ru": "жена дяди", "group": "People"},
            {"ge": "სართული", "en": "floor / storey", "ru": "этаж", "group": "Apartment"},
            {"ge": "სადარბაზო", "en": "entrance hall / stairwell", "ru": "подъезд", "group": "Apartment"},
            {"ge": "შემოსასვლელი", "en": "entrance", "ru": "вход", "group": "Apartment"},
            {"ge": "ლიფტი", "en": "elevator", "ru": "лифт", "group": "Apartment"},
            {"ge": "კიბე", "en": "stairs", "ru": "лестница", "group": "Apartment"},
            {"ge": "იატაკი", "en": "floor (surface)", "ru": "пол", "group": "Apartment"},
            {"ge": "ჭერი", "en": "ceiling", "ru": "потолок", "group": "Apartment"},
            {"ge": "ფანჯარა", "en": "window", "ru": "окно", "group": "Apartment"},
            {"ge": "კარი", "en": "door", "ru": "дверь", "group": "Apartment"},
            {"ge": "აივანი", "en": "balcony", "ru": "балкон", "group": "Apartment"},
            {"ge": "კაბინეტი", "en": "study / office room", "ru": "кабинет", "group": "Apartment"},
            {"ge": "ნათელი", "en": "bright", "ru": "светлый", "group": "Adjectives"},
            {"ge": "ბნელი", "en": "dark", "ru": "тёмный", "group": "Adjectives"},
            {"ge": "ვიწრო", "en": "narrow", "ru": "узкий", "group": "Adjectives"},
            {"ge": "ფართო", "en": "wide / spacious", "ru": "широкий", "group": "Adjectives"},
            {"ge": "კეთილი", "en": "kind", "ru": "добрый", "group": "Adjectives"},
            {"ge": "ჭკვიანი", "en": "clever", "ru": "умный", "group": "Adjectives"},
            {"ge": "ძლიერი", "en": "strong", "ru": "сильный", "group": "Adjectives"},
            {"ge": "ზემოთ", "en": "above / upstairs", "ru": "наверху", "group": "Position"},
            {"ge": "ქვემოთ", "en": "below / downstairs", "ru": "внизу", "group": "Position"},
            {"ge": "ერთმანეთი", "en": "each other", "ru": "друг друга", "group": "Useful words"},
        ],
    },
    "4": {
        "title": "Our Acquaintances",
        "grammar": {
            "en": "Ordinal numbers: მე+cardinal+ე (მეორე, მესამე), first is პირველი. Past review: იყო was, ჰყავდა had (person), ჰქონდა had (thing). Reported speech uses -ო.",
            "ru": "Порядковые числительные: მე+числительное+ე (მეორე, მესამე), первый = პირველი. Повторение прошедшего: იყო, ჰყავდა, ჰქონდა. В косвенной речи часто используется -ო.",
            "example_ge": "ის ცნობილი ფეხბურთელი იყო და ყველა ყოჩაღო ეუბნებოდა.",
            "example_en": "He was a famous footballer and everyone told him 'bravo'.",
        },
        "easier_than_russian": "Ordinal formation is regular after პირველი, so fewer irregular patterns to memorize.",
        "vocab": [
            {"ge": "დიასახლისი", "en": "housewife", "ru": "домохозяйка", "group": "Professions"},
            {"ge": "პენსიონერი", "en": "pensioner", "ru": "пенсионер", "group": "Professions"},
            {"ge": "უმუშევარი", "en": "unemployed", "ru": "безработный", "group": "Professions"},
            {"ge": "ეკონომისტი", "en": "economist", "ru": "экономист", "group": "Professions"},
            {"ge": "ბანკირი", "en": "banker", "ru": "банкир", "group": "Professions"},
            {"ge": "ფეხბურთელი", "en": "footballer", "ru": "футболист", "group": "Professions"},
            {"ge": "გამხდარი", "en": "slim / thin", "ru": "стройный", "group": "Descriptions"},
            {"ge": "მსუქანი", "en": "fat", "ru": "полный", "group": "Descriptions"},
            {"ge": "წყნარი", "en": "calm / quiet", "ru": "спокойный", "group": "Descriptions"},
            {"ge": "მხიარული", "en": "cheerful", "ru": "весёлый", "group": "Descriptions"},
            {"ge": "დაკავებული", "en": "busy", "ru": "занятый", "group": "Descriptions"},
            {"ge": "მნიშვნელოვანი", "en": "important", "ru": "важный", "group": "Descriptions"},
            {"ge": "მდიდარი", "en": "rich", "ru": "богатый", "group": "Descriptions"},
            {"ge": "ღარიბი", "en": "poor", "ru": "бедный", "group": "Descriptions"},
            {"ge": "ცნობილი", "en": "famous", "ru": "известный", "group": "Descriptions"},
            {"ge": "შავგვრემანი", "en": "dark-haired", "ru": "темноволосый", "group": "Descriptions"},
            {"ge": "ქერა", "en": "blond / fair-haired", "ru": "светловолосый", "group": "Descriptions"},
            {"ge": "წითური", "en": "red-haired", "ru": "рыжий", "group": "Descriptions"},
            {"ge": "გასათხოვარი", "en": "unmarried (woman)", "ru": "незамужняя", "group": "Relationship status"},
            {"ge": "გათხოვილი", "en": "married (woman)", "ru": "замужняя", "group": "Relationship status"},
            {"ge": "ცოლიანი", "en": "married (man)", "ru": "женатый", "group": "Relationship status"},
            {"ge": "უცოლო", "en": "unmarried (man)", "ru": "холостой", "group": "Relationship status"},
            {"ge": "საქმრო", "en": "fiance", "ru": "жених", "group": "Relationship status"},
            {"ge": "საცოლე", "en": "fiancee", "ru": "невеста", "group": "Relationship status"},
            {"ge": "ქორწილი", "en": "wedding", "ru": "свадьба", "group": "Relationship status"},
            {"ge": "ყოჩაღ", "en": "well done! / bravo!", "ru": "молодец!", "group": "Useful words"},
        ],
    },
    "5": {
        "title": "Foreign Guest in Tbilisi",
        "grammar": {
            "en": "Adjective degrees: comparative with უფრო...ვიდრე and superlative with ყველაზე + adjective. Indefinite pronouns: რამე, ვინმე, სადმე, არავინ, არაფერი.",
            "ru": "Степени сравнения: сравнительная უფრო...ვიდრე, превосходная ყველაზე + прилагательное. Неопределенные местоимения: რამე, ვინმე, სადმე, არავინ, არაფერი.",
            "example_ge": "ეს ყველაზე საინტერესო ხიდია ქალაქში.",
            "example_en": "This is the most interesting bridge in the city.",
        },
        "easier_than_russian": "One stable superlative marker (ყველაზე) replaces many Russian adjective endings.",
        "vocab": [
            {"ge": "სასტუმრო", "en": "hotel", "ru": "отель", "group": "City sightseeing"},
            {"ge": "ციხე", "en": "fortress / castle", "ru": "крепость", "group": "City sightseeing"},
            {"ge": "ეკლესია", "en": "church", "ru": "церковь", "group": "City sightseeing"},
            {"ge": "გოგირდი", "en": "sulfur", "ru": "сера", "group": "City sightseeing"},
            {"ge": "სტილი", "en": "style", "ru": "стиль", "group": "City sightseeing"},
            {"ge": "არქიტექტურა", "en": "architecture", "ru": "архитектура", "group": "City sightseeing"},
            {"ge": "ისტორიკოსი", "en": "historian", "ru": "историк", "group": "People"},
            {"ge": "მოგზაური", "en": "traveler", "ru": "путешественник", "group": "People"},
            {"ge": "მიწა", "en": "land / earth", "ru": "земля", "group": "City sightseeing"},
            {"ge": "ხიდი", "en": "bridge", "ru": "мост", "group": "City sightseeing"},
            {"ge": "შესანიშნავი", "en": "wonderful / magnificent", "ru": "замечательный", "group": "Adjectives"},
            {"ge": "მთავარი", "en": "main", "ru": "главный", "group": "Adjectives"},
            {"ge": "აუცილებელი", "en": "necessary", "ru": "необходимый", "group": "Adjectives"},
            {"ge": "საკმარისი", "en": "sufficient", "ru": "достаточный", "group": "Adjectives"},
            {"ge": "დასასვენებელი", "en": "recreational / for отдыха", "ru": "для отдыха", "group": "Adjectives"},
            {"ge": "იმედი", "en": "hope", "ru": "надежда", "group": "Useful words"},
            {"ge": "იმედია", "en": "hopefully", "ru": "надеюсь", "group": "Useful words"},
            {"ge": "ჩანს", "en": "it seems / is visible", "ru": "кажется / видно", "group": "Useful words"},
            {"ge": "რამე", "en": "something", "ru": "что-то", "group": "Pronouns"},
            {"ge": "ვინმე", "en": "someone", "ru": "кто-то", "group": "Pronouns"},
            {"ge": "სადმე", "en": "somewhere", "ru": "где-то", "group": "Pronouns"},
            {"ge": "რამდენიმე", "en": "a few / several", "ru": "несколько", "group": "Pronouns"},
            {"ge": "არავინ", "en": "nobody", "ru": "никто", "group": "Pronouns"},
            {"ge": "არაფერი", "en": "nothing", "ru": "ничего", "group": "Pronouns"},
        ],
    },
    "6": {
        "title": "My One Day",
        "grammar": {
            "en": "Comparative: უფრო...ვიდრე (more...than). Equality: ისეთივე...როგორც (as...as). Daily adverbs: ჩვეულებრივ usually, ხანდახან sometimes, თითქმის almost.",
            "ru": "Сравнение: უფრო...ვიდრე (более...чем). Равенство: ისეთივე...როგორც (такой же...как). Наречия: ჩვეულებრივ обычно, ხანდახან иногда, თითქმის почти.",
            "example_ge": "ჩემი დილა უფრო სწრაფია, ვიდრე ჩემი საღამო.",
            "example_en": "My morning is faster-paced than my evening.",
        },
        "easier_than_russian": "Daily routine phrases are straightforward: no aspect pairs like делать/сделать.",
        "vocab": [
            {"ge": "ჭიქა", "en": "glass / cup", "ru": "стакан / чашка", "group": "Kitchen"},
            {"ge": "თეფში", "en": "plate", "ru": "тарелка", "group": "Kitchen"},
            {"ge": "ჩანგალი", "en": "fork", "ru": "вилка", "group": "Kitchen"},
            {"ge": "დანა", "en": "knife", "ru": "нож", "group": "Kitchen"},
            {"ge": "სუფრა", "en": "table setting / tablecloth", "ru": "скатерть / накрытый стол", "group": "Kitchen"},
            {"ge": "ღუმელი", "en": "oven", "ru": "духовка", "group": "Kitchen"},
            {"ge": "კარადა", "en": "cupboard", "ru": "шкаф", "group": "Kitchen"},
            {"ge": "მოხარშული", "en": "boiled", "ru": "вареный", "group": "Food description"},
            {"ge": "შემწვარი", "en": "fried / roasted", "ru": "жареный", "group": "Food description"},
            {"ge": "ტკბილი", "en": "sweet", "ru": "сладкий", "group": "Food description"},
            {"ge": "ცხარე", "en": "spicy / hot", "ru": "острый", "group": "Food description"},
            {"ge": "უმარილო", "en": "unsalted", "ru": "несоленый", "group": "Food description"},
            {"ge": "ნედლი", "en": "raw", "ru": "сырой", "group": "Food description"},
            {"ge": "ღია", "en": "light (shade)", "ru": "светлый", "group": "Adjectives"},
            {"ge": "მუქი", "en": "dark (shade)", "ru": "темный", "group": "Adjectives"},
            {"ge": "სუფთა", "en": "clean", "ru": "чистый", "group": "Adjectives"},
            {"ge": "სწრაფი", "en": "fast", "ru": "быстрый", "group": "Adjectives"},
            {"ge": "ნელი", "en": "slow", "ru": "медленный", "group": "Adjectives"},
            {"ge": "იბანს", "en": "washes (oneself)", "ru": "умывается", "group": "Daily verbs"},
            {"ge": "იღებს შხაპს", "en": "takes a shower", "ru": "принимает душ", "group": "Daily verbs"},
            {"ge": "ამზადებს", "en": "prepares / cooks", "ru": "готовит", "group": "Daily verbs"},
            {"ge": "ჩვეულებრივ", "en": "usually", "ru": "обычно", "group": "Adverbs"},
            {"ge": "ხანდახან", "en": "sometimes", "ru": "иногда", "group": "Adverbs"},
            {"ge": "ძირითადად", "en": "mainly", "ru": "в основном", "group": "Adverbs"},
        ],
    },
    "7": {
        "title": "Weekend",
        "grammar": {
            "en": "Subjunctive/reported speech patterns often use -ო in indirect speech. Conjunctions: და, მაგრამ, ან, თუ, რომ, იმიტომ რომ, თუმცა. A2 word-building suffixes: -ად, -ური, -იანი.",
            "ru": "Косвенная речь и сослагательные конструкции часто используют -ო. Союзы: და, მაგრამ, ან, თუ, რომ, იმიტომ რომ, თუმცა. Словообразование: -ად, -ური, -იანი.",
            "example_ge": "ვიცი, რომ ბაზარში დიდი არჩევანია, მაგრამ ყველაფერი იაფი არ არის.",
            "example_en": "I know that there is a big selection at the market, but not everything is cheap.",
        },
        "easier_than_russian": "Conjunctions are fixed words and do not trigger case changes like many Russian prepositions.",
        "vocab": [
            {"ge": "ხილი", "en": "fruit", "ru": "фрукты", "group": "Fruit"},
            {"ge": "ვაშლი", "en": "apple", "ru": "яблоко", "group": "Fruit"},
            {"ge": "მსხალი", "en": "pear", "ru": "груша", "group": "Fruit"},
            {"ge": "ატამი", "en": "peach", "ru": "персик", "group": "Fruit"},
            {"ge": "ბალი", "en": "cherry", "ru": "черешня", "group": "Fruit"},
            {"ge": "ალუბალი", "en": "sour cherry", "ru": "вишня", "group": "Fruit"},
            {"ge": "მარწყვი", "en": "strawberry", "ru": "клубника", "group": "Fruit"},
            {"ge": "ფორთოხალი", "en": "orange", "ru": "апельсин", "group": "Fruit"},
            {"ge": "კივი", "en": "kiwi", "ru": "киви", "group": "Fruit"},
            {"ge": "გრეიპფრუტი", "en": "grapefruit", "ru": "грейпфрут", "group": "Fruit"},
            {"ge": "ფეიხოა", "en": "feijoa", "ru": "фейхоа", "group": "Fruit"},
            {"ge": "საზამთრო", "en": "watermelon", "ru": "арбуз", "group": "Fruit"},
            {"ge": "ნესვი", "en": "melon", "ru": "дыня", "group": "Fruit"},
            {"ge": "კენკრა", "en": "berry", "ru": "ягода", "group": "Fruit"},
            {"ge": "სტაფილო", "en": "carrot", "ru": "морковь", "group": "Vegetables"},
            {"ge": "ჭარხალი", "en": "beet", "ru": "свекла", "group": "Vegetables"},
            {"ge": "ბოლოკი", "en": "radish", "ru": "редис", "group": "Vegetables"},
            {"ge": "ხახვი", "en": "onion", "ru": "лук", "group": "Vegetables"},
            {"ge": "ოხრახუში", "en": "parsley", "ru": "петрушка", "group": "Vegetables"},
            {"ge": "მწვანილი", "en": "greens / herbs", "ru": "зелень", "group": "Vegetables"},
            {"ge": "მჭადი", "en": "cornbread", "ru": "мчади", "group": "Georgian food"},
            {"ge": "ტყემალი", "en": "tkemali (plum sauce)", "ru": "ткемали", "group": "Georgian food"},
            {"ge": "მურაბა", "en": "jam", "ru": "варенье", "group": "Georgian food"},
            {"ge": "სუნელი", "en": "spice / seasoning", "ru": "специя", "group": "Georgian food"},
            {"ge": "არჩევანი", "en": "choice / selection", "ru": "выбор", "group": "Market"},
            {"ge": "ქოთანი", "en": "pot", "ru": "горшок", "group": "Market"},
            {"ge": "ბაზარი", "en": "market", "ru": "рынок", "group": "Market"},
        ],
    },
    "8": {
        "title": "Bank",
        "grammar": {
            "en": "Purpose nouns: სა- + stem + -ო/-ელი (საძინებელი, სასადილო, სამზარეულო). Postpositions follow genitive: კრედიტის შესახებ, კრიზისის გამო, ბანკის მიმართ.",
            "ru": "Существительные назначения: სა- + основа + -ო/-ელი (საძინებელი, სასადილო, სამზარეულო). Послелоги требуют родительного: კრედიტის შესახებ, კრიზისის გამო, ბანკის მიმართ.",
            "example_ge": "კრედიტის შესახებ კონსულტანტს დაველაპარაკები.",
            "example_en": "I will speak with a consultant about the loan.",
        },
        "easier_than_russian": "Key polite service phrases are fixed and reusable in many formal situations.",
        "vocab": [
            {"ge": "ანგარიში", "en": "account", "ru": "счет", "group": "Banking"},
            {"ge": "კრედიტი", "en": "credit / loan", "ru": "кредит", "group": "Banking"},
            {"ge": "განვადება", "en": "installment plan", "ru": "рассрочка", "group": "Banking"},
            {"ge": "გადარიცხვა", "en": "transfer", "ru": "перевод", "group": "Banking"},
            {"ge": "ჩარიცხვა", "en": "deposit", "ru": "зачисление", "group": "Banking"},
            {"ge": "სალარო", "en": "cash desk", "ru": "касса", "group": "Banking"},
            {"ge": "ბანკომატი", "en": "ATM", "ru": "банкомат", "group": "Banking"},
            {"ge": "მოლარე", "en": "cashier", "ru": "кассир", "group": "Bank staff"},
            {"ge": "კლიენტი", "en": "client", "ru": "клиент", "group": "Bank staff"},
            {"ge": "კონსულტანტი", "en": "consultant", "ru": "консультант", "group": "Bank staff"},
            {"ge": "კრედიტოფიცერი", "en": "credit officer", "ru": "кредитный специалист", "group": "Bank staff"},
            {"ge": "გასაუბრება", "en": "interview", "ru": "собеседование", "group": "Banking"},
            {"ge": "შემოსავალი", "en": "income", "ru": "доход", "group": "Documents"},
            {"ge": "პირადობის მოწმობა", "en": "ID card", "ru": "удостоверение личности", "group": "Documents"},
            {"ge": "ფიზიკური პირი", "en": "natural person", "ru": "физическое лицо", "group": "Documents"},
            {"ge": "იურიდიული პირი", "en": "legal entity", "ru": "юридическое лицо", "group": "Documents"},
            {"ge": "საპროცენტო განაკვეთი", "en": "interest rate", "ru": "процентная ставка", "group": "Documents"},
            {"ge": "ვადა", "en": "term / period", "ru": "срок", "group": "Documents"},
            {"ge": "ანკეტა", "en": "application form", "ru": "анкета", "group": "Documents"},
            {"ge": "ხელის მოწერა", "en": "signature", "ru": "подпись", "group": "Documents"},
            {"ge": "მობრძანდით", "en": "please come in", "ru": "проходите, пожалуйста", "group": "Polite phrases"},
            {"ge": "ინებეთ", "en": "here you are / please", "ru": "вот, пожалуйста", "group": "Polite phrases"},
            {"ge": "რა გნებავთ?", "en": "what do you wish?", "ru": "что желаете?", "group": "Polite phrases"},
            {"ge": "დაელოდეთ", "en": "please wait", "ru": "подождите, пожалуйста", "group": "Polite phrases"},
            {"ge": "რა თქმა უნდა", "en": "of course", "ru": "конечно", "group": "Polite phrases"},
            {"ge": "დაახლოებით", "en": "approximately", "ru": "примерно", "group": "Polite phrases"},
        ],
    },
    "9": {
        "title": "Health",
        "grammar": {
            "en": "Modal verbs: მინდა (I want), უნდა (must/should), შეიძლება (may/possible), არ შეიძლება (not allowed), შემიძლია (I can). Obligation pattern: უნდა + verb.",
            "ru": "Модальные глаголы: მინდა (хочу), უნდა (должен), შეიძლება (можно), არ შეიძლება (нельзя), შემიძლია (могу). Обязанность: უნდა + глагол.",
            "example_ge": "სიცხე მაქვს და წამალი უნდა მივიღო.",
            "example_en": "I have a fever and I must take medicine.",
        },
        "easier_than_russian": "Modal words are highly reusable and do not inflect by gender.",
        "vocab": [
            {"ge": "წამალი", "en": "medicine", "ru": "лекарство", "group": "Medical items"},
            {"ge": "თერმომეტრი", "en": "thermometer", "ru": "термометр", "group": "Medical items"},
            {"ge": "წნევის აპარატი", "en": "blood pressure monitor", "ru": "тонометр", "group": "Medical items"},
            {"ge": "ანალიზი", "en": "test / analysis", "ru": "анализ", "group": "Medical items"},
            {"ge": "ექიმი", "en": "doctor", "ru": "врач", "group": "People"},
            {"ge": "ექთანი", "en": "nurse", "ru": "медсестра", "group": "People"},
            {"ge": "პაციენტი", "en": "patient", "ru": "пациент", "group": "People"},
            {"ge": "მკურნალობა", "en": "treatment", "ru": "лечение", "group": "Medical care"},
            {"ge": "მკლავი", "en": "arm", "ru": "рука (от плеча)", "group": "Body"},
            {"ge": "მუხლი", "en": "knee", "ru": "колено", "group": "Body"},
            {"ge": "შუბლი", "en": "forehead", "ru": "лоб", "group": "Body"},
            {"ge": "თითი", "en": "finger", "ru": "палец", "group": "Body"},
            {"ge": "გაციებული ვარ", "en": "I have a cold", "ru": "я простужен(а)", "group": "Symptoms"},
            {"ge": "ავად ვარ", "en": "I am ill", "ru": "я болен / больна", "group": "Symptoms"},
            {"ge": "სიცხე მაქვს", "en": "I have a fever", "ru": "у меня температура", "group": "Symptoms"},
            {"ge": "გტკივა?", "en": "does it hurt?", "ru": "болит?", "group": "Symptoms"},
            {"ge": "მტკივა", "en": "it hurts", "ru": "болит", "group": "Symptoms"},
            {"ge": "გაგსინჯავთ", "en": "I will examine you", "ru": "я вас осмотрю", "group": "Clinic phrases"},
            {"ge": "მინდა", "en": "I want", "ru": "я хочу", "group": "Modal verbs"},
            {"ge": "უნდა", "en": "must / should", "ru": "нужно / должен", "group": "Modal verbs"},
            {"ge": "შეიძლება", "en": "it is possible / may", "ru": "можно", "group": "Modal verbs"},
            {"ge": "არ შეიძლება", "en": "it is not allowed", "ru": "нельзя", "group": "Modal verbs"},
            {"ge": "შემიძლია", "en": "I can", "ru": "я могу", "group": "Modal verbs"},
            {"ge": "არ შემიძლია", "en": "I cannot", "ru": "я не могу", "group": "Modal verbs"},
        ],
    },
    "10": {
        "title": "Everything for the New Apartment",
        "grammar": {
            "en": "Imperative mood: informal (შენ) vs formal (თქვენ, often -ეთ). Contracted nouns in oblique cases: მეგობარი → მეგობრის, კალამი → კალმის.",
            "ru": "Повелительное наклонение: неформальное (შენ) и формальное (თქვენ, часто -ეთ). Сжатые основы в косвенных падежах: მეგობარი → მეგობრის, კალამი → კალმის.",
            "example_ge": "მობრძანდით, ინებეთ და დაწერეთ თქვენი მისამართი.",
            "example_en": "Please come in, here you are, and write your address.",
        },
        "easier_than_russian": "Formal imperative is usually predictable with -ეთ, which makes polite commands easy to build.",
        "vocab": [
            {"ge": "სარკე", "en": "mirror", "ru": "зеркало", "group": "Furniture"},
            {"ge": "თარო", "en": "shelf", "ru": "полка", "group": "Furniture"},
            {"ge": "ფარდა", "en": "curtain", "ru": "штора", "group": "Furniture"},
            {"ge": "ტახტი", "en": "sofa-bed / couch", "ru": "диван", "group": "Furniture"},
            {"ge": "კომოდი", "en": "chest of drawers", "ru": "комод", "group": "Furniture"},
            {"ge": "ტუმბო", "en": "nightstand", "ru": "тумбочка", "group": "Furniture"},
            {"ge": "ჭაღი", "en": "chandelier", "ru": "люстра", "group": "Furniture"},
            {"ge": "ელექტროქურა", "en": "electric stove", "ru": "электроплита", "group": "Appliances"},
            {"ge": "მიკროტალღური", "en": "microwave", "ru": "микроволновка", "group": "Appliances"},
            {"ge": "სარეცხი მანქანა", "en": "washing machine", "ru": "стиральная машина", "group": "Appliances"},
            {"ge": "ჭურჭლის სარეცხი მანქანა", "en": "dishwasher", "ru": "посудомоечная машина", "group": "Appliances"},
            {"ge": "ელექტროჩაიდანი", "en": "electric kettle", "ru": "электрочайник", "group": "Appliances"},
            {"ge": "ტოსტერი", "en": "toaster", "ru": "тостер", "group": "Appliances"},
            {"ge": "ღუმელი", "en": "oven", "ru": "духовка", "group": "Appliances"},
            {"ge": "ვერცხლისფერი", "en": "silver", "ru": "серебристый", "group": "Colors"},
            {"ge": "ოქროსფერი", "en": "golden", "ru": "золотистый", "group": "Colors"},
            {"ge": "ვარდისფერი", "en": "pink", "ru": "розовый", "group": "Colors"},
            {"ge": "ყავისფერი", "en": "brown", "ru": "коричневый", "group": "Colors"},
            {"ge": "ღია", "en": "light (shade)", "ru": "светлый", "group": "Colors"},
            {"ge": "მუქი", "en": "dark (shade)", "ru": "темный", "group": "Colors"},
            {"ge": "წაიკითხეთ", "en": "read! (formal)", "ru": "прочитайте!", "group": "Imperative"},
            {"ge": "მოისმინეთ", "en": "listen! (formal)", "ru": "послушайте!", "group": "Imperative"},
            {"ge": "დაწერეთ", "en": "write! (formal)", "ru": "напишите!", "group": "Imperative"},
            {"ge": "მობრძანდით", "en": "please come in", "ru": "проходите, пожалуйста", "group": "Imperative"},
        ],
    },
    "11": {
        "title": "At the Wine Festival",
        "grammar": {
            "en": "Diminutive/slight degree: მო- prefix (მოტკბო, მომჟავო). Location expressions with postpositions and local markers: -ში, -ზე, -თან, წინ, უკან, გვერდით.",
            "ru": "Ослабленная степень качества: префикс მო- (მოტკბო, მომჟავო). Локация через послелоги и локативы: -ში, -ზე, -თან, წინ, უკან, გვერდით.",
            "example_ge": "ეს ღვინო მოტკბოა და სასიამოვნო სუნი აქვს.",
            "example_en": "This wine is slightly sweet and has a pleasant aroma.",
        },
        "easier_than_russian": "Wine descriptors are productive: adding მო- often gives a natural 'slightly' meaning.",
        "vocab": [
            {"ge": "გემო", "en": "taste / flavor", "ru": "вкус", "group": "Wine tasting"},
            {"ge": "სუნი", "en": "smell / aroma", "ru": "запах / аромат", "group": "Wine tasting"},
            {"ge": "მშრალი", "en": "dry", "ru": "сухой", "group": "Wine tasting"},
            {"ge": "ნახევრად ტკბილი", "en": "semi-sweet", "ru": "полусладкий", "group": "Wine tasting"},
            {"ge": "ნახევრად მშრალი", "en": "semi-dry", "ru": "полусухой", "group": "Wine tasting"},
            {"ge": "მოტკბო", "en": "slightly sweet", "ru": "слегка сладкий", "group": "Wine tasting"},
            {"ge": "მომჟავო", "en": "slightly sour", "ru": "слегка кислый", "group": "Wine tasting"},
            {"ge": "მწარე", "en": "bitter", "ru": "горький", "group": "Wine tasting"},
            {"ge": "მჟავე", "en": "sour", "ru": "кислый", "group": "Wine tasting"},
            {"ge": "ტკბილი", "en": "sweet", "ru": "сладкий", "group": "Wine tasting"},
            {"ge": "დოქი", "en": "clay pitcher", "ru": "кувшин", "group": "Wine vessels"},
            {"ge": "ყანწი", "en": "drinking horn", "ru": "рог для вина", "group": "Wine vessels"},
            {"ge": "სასმისი", "en": "drinking vessel", "ru": "бокал / сосуд", "group": "Wine vessels"},
            {"ge": "სასმელი", "en": "beverage", "ru": "напиток", "group": "Wine vessels"},
            {"ge": "მწარმოებელი", "en": "producer", "ru": "производитель", "group": "Festival"},
            {"ge": "წარმოება", "en": "production", "ru": "производство", "group": "Festival"},
            {"ge": "კუთხე", "en": "region / corner", "ru": "регион / угол", "group": "Festival"},
            {"ge": "მოკრეფილი", "en": "harvested", "ru": "собранный", "group": "Festival"},
            {"ge": "ირგვლივ", "en": "around", "ru": "вокруг", "group": "Location"},
            {"ge": "უკან", "en": "behind / back", "ru": "сзади", "group": "Location"},
            {"ge": "წინ", "en": "in front", "ru": "впереди / перед", "group": "Location"},
            {"ge": "შუაში", "en": "in the middle", "ru": "посередине", "group": "Location"},
            {"ge": "გვერდით", "en": "beside", "ru": "рядом", "group": "Location"},
            {"ge": "ზემოთ", "en": "above", "ru": "сверху", "group": "Location"},
        ],
    },
    "12": {
        "title": "Guest in a Georgian Family",
        "grammar": {
            "en": "Similative comparison: X-ის მსგავსი (similar to X), X-ივით (like X), ისეთი...როგორც (such...as). Advanced contracted stems continue in oblique forms.",
            "ru": "Сравнение по сходству: X-ის მსგავსი (похожий на X), X-ივით (как X), ისეთი...როგორც (такой...как). Продолжается тема сжатых основ в косвенных формах.",
            "example_ge": "სტუმარი ღვთისაა და მასპინძელი გულით ხვდება.",
            "example_en": "A guest is from God, and the host welcomes them warmly.",
        },
        "easier_than_russian": "Pattern -ივით is very direct for 'like/as', without separate case prepositions.",
        "vocab": [
            {"ge": "სტუმარი", "en": "guest", "ru": "гость", "group": "Hospitality"},
            {"ge": "მასპინძელი", "en": "host", "ru": "хозяин / принимающая сторона", "group": "Hospitality"},
            {"ge": "სუფრა", "en": "feast table setting", "ru": "застолье / стол", "group": "Hospitality"},
            {"ge": "თამადა", "en": "toastmaster", "ru": "тамада", "group": "Hospitality"},
            {"ge": "სადღეგრძელო", "en": "toast", "ru": "тост", "group": "Hospitality"},
            {"ge": "ტრადიცია", "en": "tradition", "ru": "традиция", "group": "Hospitality"},
            {"ge": "ტკბილეული", "en": "sweets", "ru": "сладости", "group": "Food"},
            {"ge": "მწნილეული", "en": "pickled vegetables", "ru": "соленья", "group": "Food"},
            {"ge": "ხეხილი", "en": "fruit trees / fruit", "ru": "плодовые деревья / фрукты", "group": "Food"},
            {"ge": "ისპანახი", "en": "spinach", "ru": "шпинат", "group": "Food"},
            {"ge": "სასახლე", "en": "palace", "ru": "дворец", "group": "House and place"},
            {"ge": "საფლავი", "en": "grave / tomb", "ru": "могила", "group": "House and place"},
            {"ge": "შვილთაშვილი", "en": "grandchild", "ru": "внук / внучка", "group": "Family"},
            {"ge": "მზარეული", "en": "cook / chef", "ru": "повар", "group": "People"},
            {"ge": "თარჯიმანი", "en": "translator / interpreter", "ru": "переводчик", "group": "People"},
            {"ge": "თაობა", "en": "generation", "ru": "поколение", "group": "People"},
            {"ge": "მყუდრო", "en": "cozy", "ru": "уютный", "group": "Adjectives"},
            {"ge": "ცოცხალი", "en": "alive / lively", "ru": "живой", "group": "Adjectives"},
            {"ge": "ხალისიანი", "en": "cheerful / fun", "ru": "веселый", "group": "Adjectives"},
            {"ge": "სახალისო", "en": "entertaining", "ru": "занимательный", "group": "Adjectives"},
            {"ge": "სქელი", "en": "thick", "ru": "толстый / густой", "group": "Adjectives"},
            {"ge": "თხელი", "en": "thin", "ru": "тонкий", "group": "Adjectives"},
            {"ge": "ხედი", "en": "view", "ru": "вид", "group": "Adjectives"},
            {"ge": "ბავშვივით", "en": "like a child", "ru": "как ребенок", "group": "Comparison"},
        ],
    },
}


def main():
    with open(LESSON_DATA, encoding="utf-8") as f:
        data = json.load(f)
    data["a2"] = A2
    with open(LESSON_DATA, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    counts = {k: len(v["vocab"]) for k, v in A2.items()}
    print(f"✅ Updated A2 with {len(A2)} lessons in {LESSON_DATA}")
    for k in sorted(counts, key=int):
        print(f"   L{k}: {counts[k]} words — {A2[k]['title']}")


if __name__ == "__main__":
    main()
