#!/usr/bin/env python3
"""Merge A2+ აღმართი lessons into lesson_data.json."""

import json

from config import LESSON_DATA

A2PLUS = {
    "1": {
        "title": "National Product & Export",
        "grammar": {
            "en": "Passive voice (მიმღეობა): stem + -ებ-ა/ებ-ს — ძლიერდება (strengthens), საქმდება (jobs are created), იზრდება (grows). Export: ექსპორტი / ექსპორტირება. Import: იმპორტი.",
            "ru": "Пассив: основа + -ებ-а/ებ-ს — ძლიერდება (укрепляется), საქმდება (создаются рабочие места), იზრდება (растет). Экспорт/импорт.",
            "example_ge": "საქართველოდან ღვინო ათეულობით ქვეყანაში ექსპორტირებულია.",
            "example_en": "Wine from Georgia is exported to dozens of countries.",
        },
        "easier_than_russian": "Passive is formed with -ებ- like a regular suffix — no auxiliary 'to be' needed.",
        "vocab": [
            {"ge": "ეროვნული პროდუქტი", "en": "national product", "ru": "национальный продукт", "group": "economy"},
            {"ge": "ექსპორტი", "en": "export", "ru": "экспорт", "group": "trade"},
            {"ge": "იმპორტი", "en": "import", "ru": "импорт", "group": "trade"},
            {"ge": "წარმოება", "en": "production / manufacturing", "ru": "производство", "group": "industry"},
            {"ge": "ინვესტიცია", "en": "investment", "ru": "инвестиция", "group": "finance"},
            {"ge": "ბიუჯეტი", "en": "budget", "ru": "бюджет", "group": "finance"},
            {"ge": "ვალუტა", "en": "currency", "ru": "валюта", "group": "finance"},
            {"ge": "საწარმო", "en": "enterprise / factory", "ru": "предприятие", "group": "industry"},
            {"ge": "ექსპორტირება", "en": "to export", "ru": "экспортировать", "group": "trade"},
            {"ge": "პოპულარული", "en": "popular", "ru": "популярный", "group": "market"},
            {"ge": "მოთხოვნა", "en": "demand", "ru": "спрос", "group": "market"},
            {"ge": "ღირებულება", "en": "value / cost", "ru": "стоимость", "group": "finance"},
            {"ge": "საერთაშორისო", "en": "international", "ru": "международный", "group": "trade"},
            {"ge": "ძლიერდება", "en": "is strengthening", "ru": "укрепляется", "group": "trend"},
            {"ge": "იზრდება", "en": "is growing", "ru": "растет", "group": "trend"},
            {"ge": "საქმდება", "en": "jobs are created", "ru": "трудоустраиваются", "group": "employment"},
            {"ge": "ეკონომიკა", "en": "economy", "ru": "экономика", "group": "economy"},
            {"ge": "შემოსავალი", "en": "income / revenue", "ru": "доход", "group": "finance"},
            {"ge": "მოგება", "en": "profit", "ru": "прибыль", "group": "finance"},
            {"ge": "დანახარჯი", "en": "expense", "ru": "расход", "group": "finance"},
            {"ge": "ადგილობრივი", "en": "local", "ru": "местный", "group": "market"},
            {"ge": "საგარეო ბაზარი", "en": "foreign market", "ru": "внешний рынок", "group": "trade"},
        ],
    },
    "2": {
        "title": "Agrohub & Product Labels",
        "grammar": {
            "en": "Adjectives from nouns: -იანი (quality), -ური (origin). Genitive + postposition: პროდუქტის შესახებ (about the product), ვადის გამო (because of expiry).",
            "ru": "Прилагательные: -იანი (качество), -ური (происхождение). Родительный + послелог: შესახებ (о), გამო (из-за).",
            "example_ge": "ეტიკეტზე პროდუქტის შემადგენლობა და ვადაა მითითებული.",
            "example_en": "The label shows the product ingredients and expiry date.",
        },
        "easier_than_russian": "Label vocabulary is mostly international loanwords — ორგანული, კალორია, ეკოლოგიური.",
        "vocab": [
            {"ge": "აგროჰაბი", "en": "agrohub (farm market)", "ru": "агрохаб", "group": "retail"},
            {"ge": "ეტიკეტი", "en": "label", "ru": "этикетка", "group": "packaging"},
            {"ge": "ნატურალური", "en": "natural", "ru": "натуральный", "group": "quality"},
            {"ge": "ორგანული", "en": "organic", "ru": "органический", "group": "quality"},
            {"ge": "კალორია", "en": "calorie", "ru": "калория", "group": "nutrition"},
            {"ge": "ცხიმიანობა", "en": "fat content", "ru": "жирность", "group": "nutrition"},
            {"ge": "ვადა", "en": "expiry date / term", "ru": "срок", "group": "labeling"},
            {"ge": "მწარმოებელი", "en": "producer / manufacturer", "ru": "производитель", "group": "supply"},
            {"ge": "ხელნაკეთი", "en": "handmade", "ru": "ручной работы", "group": "quality"},
            {"ge": "ქარხნული", "en": "factory-made", "ru": "заводской", "group": "production"},
            {"ge": "ბუნებრივი", "en": "natural", "ru": "природный", "group": "quality"},
            {"ge": "ხელოვნური", "en": "artificial", "ru": "искусственный", "group": "quality"},
            {"ge": "ნედლეული", "en": "raw material", "ru": "сырье", "group": "production"},
            {"ge": "შესახებ", "en": "about / regarding", "ru": "о", "group": "language"},
            {"ge": "შემადგენლობა", "en": "ingredients / composition", "ru": "состав", "group": "labeling"},
            {"ge": "სერტიფიკატი", "en": "certificate", "ru": "сертификат", "group": "quality"},
            {"ge": "ეკოლოგიური", "en": "eco-friendly", "ru": "экологичный", "group": "quality"},
            {"ge": "შეფუთვა", "en": "packaging", "ru": "упаковка", "group": "packaging"},
            {"ge": "წონა", "en": "weight", "ru": "вес", "group": "labeling"},
            {"ge": "მოცულობა", "en": "volume", "ru": "объем", "group": "labeling"},
            {"ge": "ფასდაკლება", "en": "discount", "ru": "скидка", "group": "retail"},
            {"ge": "ფასიანი", "en": "priced / costly", "ru": "стоимостной", "group": "retail"},
        ],
    },
    "3": {
        "title": "Emergency 112",
        "grammar": {
            "en": "Obligation: აუცილებელია + verb. Instruction language uses polite imperative forms. Question particle ხომ softens urgent questions.",
            "ru": "Обязанность: აუცილებელია + глагол. Инструкции: вежливый императив. Частица ხომ смягчает вопрос.",
            "example_ge": "თუ საფრთხეა, აუცილებელია დაუყოვნებლივ დარეკოთ 112-ზე.",
            "example_en": "If there is danger, you must call 112 immediately.",
        },
        "easier_than_russian": "112 is 'ას თორმეტი' — same emergency number logic as 911.",
        "vocab": [
            {"ge": "საგანგებო", "en": "emergency", "ru": "экстренный", "group": "emergency"},
            {"ge": "გადაუდებელი", "en": "urgent", "ru": "срочный", "group": "emergency"},
            {"ge": "თვითმხილველი", "en": "eyewitness", "ru": "очевидец", "group": "reporting"},
            {"ge": "სისხლდენა", "en": "bleeding", "ru": "кровотечение", "group": "medical"},
            {"ge": "ხანძარი", "en": "fire", "ru": "пожар", "group": "fire"},
            {"ge": "ავარია", "en": "accident", "ru": "авария", "group": "incident"},
            {"ge": "საფრთხე", "en": "danger / threat", "ru": "опасность", "group": "emergency"},
            {"ge": "დაუყოვნებლივ", "en": "immediately", "ru": "немедленно", "group": "urgency"},
            {"ge": "დარეკეთ", "en": "call! (formal)", "ru": "позвоните", "group": "communication"},
            {"ge": "ოპერატორი", "en": "operator", "ru": "оператор", "group": "communication"},
            {"ge": "აუცილებელია", "en": "it is necessary", "ru": "необходимо", "group": "grammar"},
            {"ge": "სასწრაფო", "en": "ambulance / urgent", "ru": "скорая помощь", "group": "medical"},
            {"ge": "ინსტრუქცია", "en": "instruction", "ru": "инструкция", "group": "communication"},
            {"ge": "გახდით", "en": "become! (formal)", "ru": "станьте", "group": "grammar"},
            {"ge": "პოლიცია", "en": "police", "ru": "полиция", "group": "services"},
            {"ge": "სახანძრო", "en": "fire service", "ru": "пожарная служба", "group": "services"},
            {"ge": "სასწრაფო დახმარება", "en": "ambulance service", "ru": "скорая помощь", "group": "services"},
            {"ge": "დაშავებული", "en": "injured person", "ru": "пострадавший", "group": "medical"},
            {"ge": "უგონოდ", "en": "unconscious", "ru": "без сознания", "group": "medical"},
            {"ge": "მისამართი", "en": "address", "ru": "адрес", "group": "reporting"},
            {"ge": "ლოკაცია", "en": "location", "ru": "локация", "group": "reporting"},
            {"ge": "დაელოდეთ", "en": "wait! (formal)", "ru": "подождите", "group": "instruction"},
        ],
    },
    "4": {
        "title": "Lost Items & Police",
        "grammar": {
            "en": "Describing lost items: დაკარგული, დამეკარგა, მქონდა. Identification: პირადობის მოწმობა. Phone phrases: შეიძლება გკითხოთ?",
            "ru": "Потеря: დაკარგული, დამეკარგა. Идентификация: პირადობის მოწმობა. Вежливый вопрос: შეიძლება გკითხოთ?",
            "example_ge": "დაკარგული ნივთის აღწერა პოლიციაში გავაკეთე.",
            "example_en": "I gave a description of the lost item at the police station.",
        },
        "easier_than_russian": "დაკარგული is transparent — 'lost' from the same base as დაკარგვა.",
        "vocab": [
            {"ge": "დაკარგული", "en": "lost", "ru": "потерянный", "group": "lost-item"},
            {"ge": "ნივთი", "en": "item / thing", "ru": "вещь", "group": "lost-item"},
            {"ge": "საფულე", "en": "wallet", "ru": "кошелек", "group": "lost-item"},
            {"ge": "პირადობის მოწმობა", "en": "ID card", "ru": "удостоверение личности", "group": "identification"},
            {"ge": "პოლიციელი", "en": "police officer", "ru": "полицейский", "group": "police"},
            {"ge": "იდენტიფიცირება", "en": "identification", "ru": "идентификация", "group": "identification"},
            {"ge": "აღწერა", "en": "description", "ru": "описание", "group": "reporting"},
            {"ge": "დეტალი", "en": "detail", "ru": "деталь", "group": "reporting"},
            {"ge": "შემთხვევა", "en": "incident", "ru": "случай", "group": "incident"},
            {"ge": "განცხადება", "en": "statement / report", "ru": "заявление", "group": "reporting"},
            {"ge": "მოძებნა", "en": "search", "ru": "поиск", "group": "recovery"},
            {"ge": "დაკარგვა", "en": "loss", "ru": "утрата", "group": "lost-item"},
            {"ge": "შეიძლება გკითხოთ?", "en": "may I ask you?", "ru": "можно спросить?", "group": "communication"},
            {"ge": "დაბრუნება", "en": "return (an item)", "ru": "возврат", "group": "recovery"},
            {"ge": "დამეკარგა", "en": "I lost (it happened to me)", "ru": "я потерял(а)", "group": "grammar"},
            {"ge": "მფლობელი", "en": "owner", "ru": "владелец", "group": "identification"},
            {"ge": "პოვნა", "en": "finding", "ru": "нахождение", "group": "recovery"},
            {"ge": "ნაპოვნი", "en": "found", "ru": "найденный", "group": "recovery"},
            {"ge": "ოქმი", "en": "official report", "ru": "протокол", "group": "police"},
            {"ge": "განყოფილება", "en": "department", "ru": "отделение", "group": "police"},
            {"ge": "თანხა", "en": "amount of money", "ru": "сумма", "group": "lost-item"},
            {"ge": "დოკუმენტი", "en": "document", "ru": "документ", "group": "identification"},
        ],
    },
    "5": {
        "title": "Holiday Destinations & Tours",
        "grammar": {
            "en": "Tour descriptions use X-დან Y-მდე and X-დღიანი forms. შედის marks what is included; comparison uses უფრო + adjective.",
            "ru": "Описание тура: X-დან Y-მდე, X-დღიანი. შედის = входит. Сравнение: უფრო + прилагательное.",
            "example_ge": "ხუთდღიანი ტურის ღირებულებაში სასტუმრო და საუზმე შედის.",
            "example_en": "The five-day tour price includes hotel and breakfast.",
        },
        "easier_than_russian": "Tour words are international: ტური, მარშრუტი, ექსკურსია, ორგანიზატორი.",
        "vocab": [
            {"ge": "დასასვენებელი ადგილი", "en": "holiday destination", "ru": "место отдыха", "group": "travel"},
            {"ge": "მარშრუტი", "en": "route / itinerary", "ru": "маршрут", "group": "travel"},
            {"ge": "ტური", "en": "tour", "ru": "тур", "group": "travel"},
            {"ge": "ორგანიზატორი", "en": "organizer", "ru": "организатор", "group": "tour"},
            {"ge": "ექსკურსია", "en": "excursion", "ru": "экскурсия", "group": "activities"},
            {"ge": "კომფორტული", "en": "comfortable", "ru": "комфортный", "group": "quality"},
            {"ge": "ორგანიზებული", "en": "organized", "ru": "организованный", "group": "tour"},
            {"ge": "საბაგირო", "en": "cable car", "ru": "канатная дорога", "group": "transport"},
            {"ge": "სვანეთი", "en": "Svaneti", "ru": "Сванетия", "group": "destination"},
            {"ge": "შედის", "en": "is included", "ru": "входит", "group": "pricing"},
            {"ge": "საუზმე", "en": "breakfast", "ru": "завтрак", "group": "accommodation"},
            {"ge": "ღირებულება", "en": "cost / price", "ru": "стоимость", "group": "pricing"},
            {"ge": "თარიღი", "en": "date", "ru": "дата", "group": "planning"},
            {"ge": "დაჯავშნა", "en": "reservation", "ru": "бронирование", "group": "booking"},
            {"ge": "გამგზავრება", "en": "departure", "ru": "отправление", "group": "planning"},
            {"ge": "დაბრუნება", "en": "return trip", "ru": "возвращение", "group": "planning"},
            {"ge": "გიდი", "en": "guide", "ru": "гид", "group": "tour"},
            {"ge": "ტრანსფერი", "en": "transfer", "ru": "трансфер", "group": "transport"},
            {"ge": "ტურისტი", "en": "tourist", "ru": "турист", "group": "travel"},
            {"ge": "უფრო იაფი", "en": "cheaper", "ru": "дешевле", "group": "comparison"},
            {"ge": "უფრო ძვირი", "en": "more expensive", "ru": "дороже", "group": "comparison"},
            {"ge": "დღიანი", "en": "-day (duration suffix)", "ru": "дневный", "group": "grammar"},
        ],
    },
    "6": {
        "title": "Choosing a Hotel",
        "grammar": {
            "en": "Room-type compounds: ერთადგილიანი, ორადგილიანი, ორთოლიანი. Service and location vocabulary combines with nouns naturally.",
            "ru": "Сложные слова о номерах: ერთადგილიანი, ორადგილიანი, ორთოლიანი. Услуги и локация формируются прозрачно.",
            "example_ge": "ორადგილიანი ნომერი ზღვის ხედით თავისუფალია.",
            "example_en": "A twin room with a sea view is available.",
        },
        "easier_than_russian": "Hotel compound words are logical: სასტუმრო literally means a place for guests.",
        "vocab": [
            {"ge": "სასტუმრო", "en": "hotel", "ru": "отель", "group": "accommodation"},
            {"ge": "ნომერი", "en": "hotel room", "ru": "номер", "group": "room"},
            {"ge": "ორთოლიანი", "en": "double room", "ru": "двуспальная", "group": "room"},
            {"ge": "ერთადგილიანი", "en": "single room", "ru": "одноместный", "group": "room"},
            {"ge": "ორადგილიანი", "en": "twin room", "ru": "двухместный", "group": "room"},
            {"ge": "დამატებითი საწოლი", "en": "extra bed", "ru": "дополнительная кровать", "group": "amenity"},
            {"ge": "მომსახურება", "en": "service", "ru": "обслуживание", "group": "service"},
            {"ge": "რეცეფცია", "en": "reception", "ru": "ресепшн", "group": "service"},
            {"ge": "ვერანდა", "en": "veranda / balcony", "ru": "веранда", "group": "amenity"},
            {"ge": "ხედი", "en": "view", "ru": "вид", "group": "amenity"},
            {"ge": "კონდიციონერი", "en": "air conditioner", "ru": "кондиционер", "group": "amenity"},
            {"ge": "ზღვისპირა", "en": "seaside", "ru": "приморский", "group": "location"},
            {"ge": "ძველი ქალაქი", "en": "old town", "ru": "старый город", "group": "location"},
            {"ge": "ლარი", "en": "lari", "ru": "лари", "group": "payment"},
            {"ge": "ღამეში", "en": "per night", "ru": "за ночь", "group": "payment"},
            {"ge": "დაჯავშნა", "en": "booking", "ru": "бронирование", "group": "booking"},
            {"ge": "თავისუფალი", "en": "available", "ru": "свободный", "group": "booking"},
            {"ge": "დაკავებული", "en": "occupied", "ru": "занятый", "group": "booking"},
            {"ge": "ჩექ-ინი", "en": "check-in", "ru": "заселение", "group": "service"},
            {"ge": "ჩექ-აუთი", "en": "check-out", "ru": "выселение", "group": "service"},
            {"ge": "საუზმე შედის", "en": "breakfast included", "ru": "завтрак включен", "group": "pricing"},
            {"ge": "ინტერნეტი", "en": "internet / wi-fi", "ru": "интернет", "group": "amenity"},
        ],
    },
    "7": {
        "title": "Social Networks — About Me",
        "grammar": {
            "en": "Preference verbs მიყვარს / მომწონს are central. Profile language uses ჩემ შესახებ and private/public contrast.",
            "ru": "Глаголы предпочтения: მიყვარს / მომწონს. Язык профиля: ჩემ შესახებ, приватность.",
            "example_ge": "ჩემ შესახებ ვწერ, რა მუსიკა მომწონს.",
            "example_en": "In my profile I write what music I like.",
        },
        "easier_than_russian": "Social media terms are mostly direct loans: ფეისბუქი, პროფილი, ექაუნთი.",
        "vocab": [
            {"ge": "სოციალური ქსელი", "en": "social network", "ru": "соцсеть", "group": "platform"},
            {"ge": "ფეისბუქი", "en": "Facebook", "ru": "Фейсбук", "group": "platform"},
            {"ge": "პროფილი", "en": "profile", "ru": "профиль", "group": "account"},
            {"ge": "ექაუნთი", "en": "account", "ru": "аккаунт", "group": "account"},
            {"ge": "მეგობარი", "en": "friend", "ru": "друг", "group": "people"},
            {"ge": "პირადი", "en": "private / personal", "ru": "личный", "group": "privacy"},
            {"ge": "მომხმარებელი", "en": "user", "ru": "пользователь", "group": "account"},
            {"ge": "გვერდი", "en": "page", "ru": "страница", "group": "content"},
            {"ge": "გამომწერი", "en": "follower / subscriber", "ru": "подписчик", "group": "people"},
            {"ge": "პოსტი", "en": "post", "ru": "пост", "group": "content"},
            {"ge": "მიყვარს", "en": "I love", "ru": "я люблю", "group": "expression"},
            {"ge": "მომწონს", "en": "I like", "ru": "мне нравится", "group": "expression"},
            {"ge": "ჩემ შესახებ", "en": "about me", "ru": "обо мне", "group": "profile"},
            {"ge": "ვუკავშირდები", "en": "I connect to", "ru": "я связываюсь", "group": "interaction"},
            {"ge": "შეტყობინება", "en": "message", "ru": "сообщение", "group": "communication"},
            {"ge": "ლაიქი", "en": "like (reaction)", "ru": "лайк", "group": "interaction"},
            {"ge": "გაზიარება", "en": "share", "ru": "поделиться", "group": "interaction"},
            {"ge": "კომენტარი", "en": "comment", "ru": "комментарий", "group": "interaction"},
            {"ge": "პაროლი", "en": "password", "ru": "пароль", "group": "security"},
            {"ge": "კონფიდენციალური", "en": "confidential", "ru": "конфиденциальный", "group": "privacy"},
            {"ge": "საჯარო", "en": "public", "ru": "публичный", "group": "privacy"},
            {"ge": "სიახლე", "en": "news / update", "ru": "новость", "group": "content"},
        ],
    },
    "8": {
        "title": "Blogging & Vlog",
        "grammar": {
            "en": "Opinion and reaction phrases: ჩემი აზრით, მომწონს / არ მომწონს. Sharing verbs describe online audience interaction.",
            "ru": "Мнение и реакция: ჩემი აზრით, მომწონს / არ მომწონს. Глаголы обмена для онлайн-аудитории.",
            "example_ge": "ჩემი აზრით, ეს ვლოგი ძალიან საინტერესოა.",
            "example_en": "In my opinion, this vlog is very interesting.",
        },
        "easier_than_russian": "ბლოგი and ვლოგი are familiar international words.",
        "vocab": [
            {"ge": "ბლოგი", "en": "blog", "ru": "блог", "group": "format"},
            {"ge": "ვლოგი", "en": "vlog", "ru": "влог", "group": "format"},
            {"ge": "ავტორი", "en": "author", "ru": "автор", "group": "people"},
            {"ge": "ჩანაწერი", "en": "entry / post", "ru": "запись", "group": "content"},
            {"ge": "ვიდეო", "en": "video", "ru": "видео", "group": "media"},
            {"ge": "გამოწერა", "en": "subscription", "ru": "подписка", "group": "audience"},
            {"ge": "კომენტარი", "en": "comment", "ru": "комментарий", "group": "audience"},
            {"ge": "უარყოფითი", "en": "negative", "ru": "отрицательный", "group": "tone"},
            {"ge": "გაზიარება", "en": "sharing", "ru": "публикация", "group": "audience"},
            {"ge": "ემოცია", "en": "emotion", "ru": "эмоция", "group": "tone"},
            {"ge": "გრძნობა", "en": "feeling", "ru": "чувство", "group": "tone"},
            {"ge": "გამოცდილება", "en": "experience", "ru": "опыт", "group": "content"},
            {"ge": "ჩემი აზრით", "en": "in my opinion", "ru": "по-моему", "group": "opinion"},
            {"ge": "საინტერესო", "en": "interesting", "ru": "интересный", "group": "opinion"},
            {"ge": "აუდიტორია", "en": "audience", "ru": "аудитория", "group": "audience"},
            {"ge": "არხი", "en": "channel", "ru": "канал", "group": "platform"},
            {"ge": "მაყურებელი", "en": "viewer", "ru": "зритель", "group": "audience"},
            {"ge": "მოსაზრება", "en": "opinion / viewpoint", "ru": "мнение", "group": "opinion"},
            {"ge": "პოზიტიური", "en": "positive", "ru": "позитивный", "group": "tone"},
            {"ge": "რედაქტირება", "en": "editing", "ru": "редактирование", "group": "production"},
            {"ge": "სათაური", "en": "title", "ru": "заголовок", "group": "content"},
            {"ge": "აღწერა", "en": "description", "ru": "описание", "group": "content"},
        ],
    },
    "9": {
        "title": "Film Premiere",
        "grammar": {
            "en": "Invitations use მოდი ერთად წავიდეთ. Future plans are made with present-future verbs and explicit date/time.",
            "ru": "Приглашения: მოდი ერთად წავიდეთ. Планы на будущее: формы будущего + дата/время.",
            "example_ge": "მოდი, პრემიერაზე ერთად წავიდეთ და ბილეთები წინასწარ ვიყიდოთ.",
            "example_en": "Let's go to the premiere together and buy tickets in advance.",
        },
        "easier_than_russian": "Cinema words follow international patterns: პრემიერა, რეჟისორი, სპექტაკლი.",
        "vocab": [
            {"ge": "პრემიერა", "en": "premiere", "ru": "премьера", "group": "event"},
            {"ge": "ფილმი", "en": "film", "ru": "фильм", "group": "cinema"},
            {"ge": "რეჟისორი", "en": "director", "ru": "режиссер", "group": "people"},
            {"ge": "დარბაზი", "en": "hall / auditorium", "ru": "зал", "group": "venue"},
            {"ge": "სპექტაკლი", "en": "performance", "ru": "спектакль", "group": "event"},
            {"ge": "თეატრი", "en": "theatre", "ru": "театр", "group": "venue"},
            {"ge": "ბილეთი", "en": "ticket", "ru": "билет", "group": "ticketing"},
            {"ge": "მსახიობი", "en": "actor", "ru": "актер", "group": "people"},
            {"ge": "სცენა", "en": "stage / scene", "ru": "сцена", "group": "cinema"},
            {"ge": "თანამედროვე", "en": "modern", "ru": "современный", "group": "description"},
            {"ge": "მოდი", "en": "come on / let's", "ru": "давай", "group": "invitation"},
            {"ge": "ერთად", "en": "together", "ru": "вместе", "group": "invitation"},
            {"ge": "საათი", "en": "o'clock / hour", "ru": "час", "group": "time"},
            {"ge": "ფასი", "en": "price", "ru": "цена", "group": "ticketing"},
            {"ge": "კინოთეატრი", "en": "cinema", "ru": "кинотеатр", "group": "venue"},
            {"ge": "დასაწყისი", "en": "beginning / start", "ru": "начало", "group": "time"},
            {"ge": "დასასრული", "en": "ending", "ru": "конец", "group": "time"},
            {"ge": "წინასწარ", "en": "in advance", "ru": "заранее", "group": "planning"},
            {"ge": "დაჯავშნვა", "en": "ticket booking", "ru": "бронирование", "group": "ticketing"},
            {"ge": "პოსტერი", "en": "poster", "ru": "постер", "group": "promotion"},
            {"ge": "მაყურებელი", "en": "viewer / spectator", "ru": "зритель", "group": "people"},
            {"ge": "აპლოდისმენტები", "en": "applause", "ru": "аплодисменты", "group": "event"},
        ],
    },
    "10": {
        "title": "Plot & Film Reviews",
        "grammar": {
            "en": "Relative clause marker რომელიც links descriptions. Review language uses გირჩევთ, შეფასება, and genre labels.",
            "ru": "Связка რომელიც вводит определительные придаточные. Лексика рецензии: გირჩევთ, შეფასება, жанры.",
            "example_ge": "ფილმი, რომელიც გუშინ ვნახე, საინტერესო სიუჟეტით გამოირჩევა.",
            "example_en": "The film I watched yesterday stands out for its interesting storyline.",
        },
        "easier_than_russian": "რომელიც does not require gender agreement like Russian relative pronouns.",
        "vocab": [
            {"ge": "ფაბულა", "en": "plot", "ru": "фабула", "group": "narrative"},
            {"ge": "მოქმედება", "en": "action", "ru": "действие", "group": "narrative"},
            {"ge": "პერსონაჟი", "en": "character", "ru": "персонаж", "group": "narrative"},
            {"ge": "სიუჟეტი", "en": "storyline", "ru": "сюжет", "group": "narrative"},
            {"ge": "რეცენზია", "en": "review", "ru": "рецензия", "group": "review"},
            {"ge": "შეფასება", "en": "evaluation / rating", "ru": "оценка", "group": "review"},
            {"ge": "რეკომენდაცია", "en": "recommendation", "ru": "рекомендация", "group": "review"},
            {"ge": "ჟანრი", "en": "genre", "ru": "жанр", "group": "genre"},
            {"ge": "დრამა", "en": "drama", "ru": "драма", "group": "genre"},
            {"ge": "კომედია", "en": "comedy", "ru": "комедия", "group": "genre"},
            {"ge": "ტრაგედია", "en": "tragedy", "ru": "трагедия", "group": "genre"},
            {"ge": "რომელიც", "en": "which / who", "ru": "который", "group": "grammar"},
            {"ge": "გირჩევთ", "en": "I recommend", "ru": "рекомендую", "group": "review"},
            {"ge": "საბოლოოდ", "en": "in the end", "ru": "в итоге", "group": "review"},
            {"ge": "კრიტიკა", "en": "criticism", "ru": "критика", "group": "review"},
            {"ge": "მიმოხილვა", "en": "overview / review", "ru": "обзор", "group": "review"},
            {"ge": "დადებითი", "en": "positive", "ru": "положительный", "group": "review"},
            {"ge": "უარყოფითი", "en": "negative", "ru": "отрицательный", "group": "review"},
            {"ge": "სცენარი", "en": "screenplay", "ru": "сценарий", "group": "production"},
            {"ge": "გადაღება", "en": "filming", "ru": "съемка", "group": "production"},
            {"ge": "მუსიკალური გაფორმება", "en": "musical score", "ru": "музыкальное оформление", "group": "production"},
            {"ge": "მთავარი როლი", "en": "leading role", "ru": "главная роль", "group": "people"},
        ],
    },
    "11": {
        "title": "Foreigners in Georgia",
        "grammar": {
            "en": "Culture topics use იმიტომ რომ for reasons and adverbs like პირველად / ხშირად for experience frequency.",
            "ru": "Культурная тема: იმიტომ რომ для причин, პირველად / ხშირად для частоты опыта.",
            "example_ge": "უცხოელებს თავიდან კულტურული შოკი აქვთ, მაგრამ შემდეგ ადაპტირდებიან.",
            "example_en": "Foreigners often have culture shock at first, but later they adapt.",
        },
        "easier_than_russian": "ქართველოლოგი is transparent as a compound around Georgian language and studies.",
        "vocab": [
            {"ge": "უცხოელი", "en": "foreigner", "ru": "иностранец", "group": "people"},
            {"ge": "ქართველოლოგი", "en": "Georgianist", "ru": "картвелолог", "group": "study"},
            {"ge": "კულტურული შოკი", "en": "culture shock", "ru": "культурный шок", "group": "culture"},
            {"ge": "ტრადიცია", "en": "tradition", "ru": "традиция", "group": "culture"},
            {"ge": "ზნეობა", "en": "custom / morals", "ru": "нравы", "group": "culture"},
            {"ge": "ქცევა", "en": "behavior", "ru": "поведение", "group": "society"},
            {"ge": "ადაპტაცია", "en": "adaptation", "ru": "адаптация", "group": "integration"},
            {"ge": "ინტერვიუ", "en": "interview", "ru": "интервью", "group": "communication"},
            {"ge": "მოგზაური", "en": "traveler", "ru": "путешественник", "group": "people"},
            {"ge": "პირველად", "en": "for the first time", "ru": "впервые", "group": "time"},
            {"ge": "იმიტომ რომ", "en": "because", "ru": "потому что", "group": "grammar"},
            {"ge": "საზღვარი", "en": "border", "ru": "граница", "group": "mobility"},
            {"ge": "მეცადინეობა", "en": "studying", "ru": "занятия", "group": "study"},
            {"ge": "გამოცდილება", "en": "experience", "ru": "опыт", "group": "culture"},
            {"ge": "სტერეოტიპი", "en": "stereotype", "ru": "стереотип", "group": "culture"},
            {"ge": "სუფრა", "en": "traditional feast table", "ru": "застолье", "group": "culture"},
            {"ge": "მასპინძელი", "en": "host", "ru": "хозяин", "group": "people"},
            {"ge": "სტუმარი", "en": "guest", "ru": "гость", "group": "people"},
            {"ge": "პატივისცემა", "en": "respect", "ru": "уважение", "group": "society"},
            {"ge": "ჩვევა", "en": "habit", "ru": "привычка", "group": "culture"},
            {"ge": "ხშირად", "en": "often", "ru": "часто", "group": "time"},
            {"ge": "შეჩვევა", "en": "getting used to", "ru": "привыкание", "group": "integration"},
        ],
    },
    "12": {
        "title": "How to Learn a Language",
        "grammar": {
            "en": "Learning verbs: ვსწავლობ, ვიცი, ვცდილობ. Purpose uses რათა / -ისთვის; advice uses უნდა + verb.",
            "ru": "Глаголы обучения: ვსწავლობ, ვიცი, ვცდილობ. Цель: რათა / -ისთვის. Совет: უნდა + глагол.",
            "example_ge": "ენა რომ კარგად ისწავლო, ყოველდღე უნდა ივარჯიშო.",
            "example_en": "To learn a language well, you should practice every day.",
        },
        "easier_than_russian": "Language-learning vocabulary is largely international: გრამატიკა, ლექსიკა, პრაქტიკა.",
        "vocab": [
            {"ge": "ენა", "en": "language", "ru": "язык", "group": "learning"},
            {"ge": "სწავლა", "en": "study / learning", "ru": "учеба", "group": "learning"},
            {"ge": "მეთოდი", "en": "method", "ru": "метод", "group": "strategy"},
            {"ge": "გრამატიკა", "en": "grammar", "ru": "грамматика", "group": "skills"},
            {"ge": "ლექსიკა", "en": "vocabulary", "ru": "лексика", "group": "skills"},
            {"ge": "პრაქტიკა", "en": "practice", "ru": "практика", "group": "strategy"},
            {"ge": "რჩევა", "en": "advice / tip", "ru": "совет", "group": "strategy"},
            {"ge": "გაგება", "en": "understanding", "ru": "понимание", "group": "skills"},
            {"ge": "გამოხატვა", "en": "expression", "ru": "выражение", "group": "skills"},
            {"ge": "უნარი", "en": "skill", "ru": "навык", "group": "skills"},
            {"ge": "ვსწავლობ", "en": "I study", "ru": "я учусь", "group": "grammar"},
            {"ge": "ვცდილობ", "en": "I try", "ru": "я стараюсь", "group": "grammar"},
            {"ge": "რათა", "en": "so that", "ru": "чтобы", "group": "grammar"},
            {"ge": "ყოველდღე", "en": "every day", "ru": "каждый день", "group": "habit"},
            {"ge": "კითხვა", "en": "reading", "ru": "чтение", "group": "skills"},
            {"ge": "წერა", "en": "writing", "ru": "письмо", "group": "skills"},
            {"ge": "მოსმენა", "en": "listening", "ru": "аудирование", "group": "skills"},
            {"ge": "ლაპარაკი", "en": "speaking", "ru": "говорение", "group": "skills"},
            {"ge": "მახსოვრობა", "en": "memory", "ru": "память", "group": "strategy"},
            {"ge": "გამეორება", "en": "revision / repetition", "ru": "повторение", "group": "strategy"},
            {"ge": "მოტივაცია", "en": "motivation", "ru": "мотивация", "group": "habit"},
            {"ge": "მიზანი", "en": "goal", "ru": "цель", "group": "habit"},
        ],
    },
}


def main():
    with open(LESSON_DATA, encoding="utf-8") as f:
        data = json.load(f)

    data["a2plus"] = A2PLUS

    with open(LESSON_DATA, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Added A2+ ({len(A2PLUS)} lessons) to {LESSON_DATA}")
    total = 0
    for lesson_id in sorted(A2PLUS, key=int):
        lesson = A2PLUS[lesson_id]
        count = len(lesson["vocab"])
        total += count
        print(f"Lesson {lesson_id:>2} | {lesson['title']}: {count} words")
    print(f"Total A2+ vocab words: {total}")


if __name__ == "__main__":
    main()
