#!/usr/bin/env python3
"""Merge B1 აღმართი lessons into lesson_data.json. Source: Textbooks/B1 შემსწავლელის წიგნი.pdf"""

import json

from config import LESSON_DATA

B1 = {
    "1": {
        "title": "Autobiography — Goderdzi Chokhelishvili",
        "grammar": {
            "en": "Imperfect tense for past habits/narrative: იბადებოდა (was being born), მიდიოდა (was going), აღწევდა (was reaching). Biographical questions: როდის დაიბადე? სად?",
            "ru": "Имперфект для прошлого: იბადებოდა, მიდიოდა. Биография: როდის დაიბადე?",
            "example_ge": "გზაზე დავიბადე, გზაზე.",
            "example_en": "I was born on the road, on the road.",
        },
        "easier_than_russian": "Georgian imperfect uses -დ- infix — one pattern, no aspect pairs like Russian.",
        "vocab": [
            {"ge": "ავტობიოგრაფია", "en": "autobiography", "ru": "автобиография", "group": "text"},
            {"ge": "ბიოგრაფია", "en": "biography", "ru": "биография", "group": "text"},
            {"ge": "დაბადება", "en": "birth", "ru": "рождение", "group": "life event"},
            {"ge": "დაბადების ადგილი", "en": "place of birth", "ru": "место рождения", "group": "personal data"},
            {"ge": "დაბადების თარიღი", "en": "date of birth", "ru": "дата рождения", "group": "personal data"},
            {"ge": "დედა-მამა", "en": "parents", "ru": "родители", "group": "family"},
            {"ge": "ოჯახი", "en": "family", "ru": "семья", "group": "family"},
            {"ge": "წინაპარი", "en": "ancestor", "ru": "предок", "group": "family"},
            {"ge": "ბავშვობა", "en": "childhood", "ru": "детство", "group": "life stage"},
            {"ge": "მშობიარობა", "en": "childbirth", "ru": "роды", "group": "life event"},
            {"ge": "სოფელი", "en": "village", "ru": "деревня", "group": "place"},
            {"ge": "ქალაქი", "en": "city", "ru": "город", "group": "place"},
            {"ge": "რაიონი", "en": "district", "ru": "район", "group": "place"},
            {"ge": "წმინდა ადგილი", "en": "holy place", "ru": "святое место", "group": "place"},
            {"ge": "მოგონება", "en": "memory", "ru": "воспоминание", "group": "narrative"},
            {"ge": "ისტორია", "en": "story / history", "ru": "история", "group": "narrative"},
            {"ge": "ხასიათი", "en": "character / personality", "ru": "характер", "group": "personality"},
            {"ge": "მოღვაწეობა", "en": "activity / career", "ru": "деятельность", "group": "career"},
            {"ge": "გზა", "en": "road / path", "ru": "дорога", "group": "place"},
            {"ge": "იბადებოდა", "en": "was being born (impf.)", "ru": "рождался", "group": "grammar"},
            {"ge": "მიდიოდა", "en": "was going (impf.)", "ru": "шёл / ехал", "group": "grammar"},
            {"ge": "აღწევდა", "en": "was reaching (impf.)", "ru": "достигал", "group": "grammar"},
        ],
    },
    "2": {
        "title": "CV & Vacancies",
        "grammar": {
            "en": "Formal biography: მე, X, დავიბადე... (I, X, was born...). CV sections: განათლება, გამოცდილება, უნარ-ჩვევები. Dates: 2011 წელს, 2012 წლიდან – დღემდე.",
            "ru": "Формальная биография: მე, X, დავიბადე. CV: განათლება, გამოცდილება.",
            "example_ge": "2011 წელს დავამთავრე სკოლა.",
            "example_en": "In 2011 I finished school.",
        },
        "easier_than_russian": "CV structure matches international format — same sections, Georgian labels.",
        "vocab": [
            {"ge": "CV", "en": "CV / resume", "ru": "резюме", "group": "document"},
            {"ge": "რეზიუმე", "en": "resume", "ru": "резюме", "group": "document"},
            {"ge": "ვაკანსია", "en": "vacancy / job opening", "ru": "вакансия", "group": "employment"},
            {"ge": "განცხადება", "en": "announcement / ad", "ru": "объявление", "group": "employment"},
            {"ge": "თანამდებობა", "en": "position / post", "ru": "должность", "group": "employment"},
            {"ge": "განაცხადი", "en": "application", "ru": "заявление", "group": "document"},
            {"ge": "კანდიდატი", "en": "candidate", "ru": "кандидат", "group": "employment"},
            {"ge": "განათლება", "en": "education", "ru": "образование", "group": "cv section"},
            {"ge": "გამოცდილება", "en": "experience", "ru": "опыт", "group": "cv section"},
            {"ge": "პროფესიული გამოცდილება", "en": "professional experience", "ru": "профессиональный опыт", "group": "cv section"},
            {"ge": "უნარ-ჩვევები", "en": "skills", "ru": "навыки", "group": "cv section"},
            {"ge": "უცხო ენა", "en": "foreign language", "ru": "иностранный язык", "group": "cv section"},
            {"ge": "კომპიუტერული უნარები", "en": "computer skills", "ru": "компьютерные навыки", "group": "cv section"},
            {"ge": "დიპლომი", "en": "diploma", "ru": "диплом", "group": "education"},
            {"ge": "ფაკულტეტი", "en": "faculty", "ru": "факультет", "group": "education"},
            {"ge": "უნივერსიტეტი", "en": "university", "ru": "университет", "group": "education"},
            {"ge": "სტაჟირება", "en": "internship", "ru": "стажировка", "group": "experience"},
            {"ge": "დასაქმება", "en": "employment", "ru": "трудоустройство", "group": "employment"},
            {"ge": "ხელფასი", "en": "salary", "ru": "зарплата", "group": "employment"},
            {"ge": "ელფოსტა", "en": "email", "ru": "электронная почта", "group": "contact"},
            {"ge": "ტელეფონის ნომერი", "en": "phone number", "ru": "номер телефона", "group": "contact"},
            {"ge": "სამოტივაციო წერილი", "en": "motivation letter", "ru": "мотивационное письмо", "group": "document"},
        ],
    },
    "3": {
        "title": "Job Interview Prep",
        "grammar": {
            "en": "Interview traits: პუნქტუალური (punctual), პასუხისმგებელი (responsible), შემოქმედებითი (creative). Modal: შეუძლია (can), აქვს (has). Preparation: მოვემზადოთ გასაუბრებისთვის.",
            "ru": "Собеседование: პუნქტუალური, პასუხისმგებელი. Модальные: შეუძლია, აქვს.",
            "example_ge": "მას აქვს თარჯიმნობის გამოცდილება.",
            "example_en": "He/she has translation experience.",
        },
        "easier_than_russian": "გასაუბრება is transparent — 'for-conversation' = interview.",
        "vocab": [
            {"ge": "გასაუბრება", "en": "job interview", "ru": "собеседование", "group": "interview"},
            {"ge": "დამსაქმებელი", "en": "employer", "ru": "работодатель", "group": "interview"},
            {"ge": "კანდიდატი", "en": "candidate", "ru": "кандидат", "group": "interview"},
            {"ge": "შეკითხვა", "en": "question", "ru": "вопрос", "group": "interview"},
            {"ge": "პასუხი", "en": "answer", "ru": "ответ", "group": "interview"},
            {"ge": "სამუშაო გამოცდილება", "en": "work experience", "ru": "рабочий опыт", "group": "interview"},
            {"ge": "პასუხისმგებლობა", "en": "responsibility", "ru": "ответственность", "group": "qualities"},
            {"ge": "პუნქტუალური", "en": "punctual", "ru": "пунктуальный", "group": "qualities"},
            {"ge": "პასუხისმგებელი", "en": "responsible", "ru": "ответственный", "group": "qualities"},
            {"ge": "შემოქმედებითი", "en": "creative", "ru": "творческий", "group": "qualities"},
            {"ge": "კომუნიკაბელური", "en": "communicative", "ru": "коммуникабельный", "group": "qualities"},
            {"ge": "გუნდური", "en": "team-oriented", "ru": "командный", "group": "qualities"},
            {"ge": "ძლიერი მხარე", "en": "strong side", "ru": "сильная сторона", "group": "self-presentation"},
            {"ge": "სუსტი მხარე", "en": "weak side", "ru": "слабая сторона", "group": "self-presentation"},
            {"ge": "პროფესია", "en": "profession", "ru": "профессия", "group": "career"},
            {"ge": "თარჯიმნობა", "en": "translation work", "ru": "перевод", "group": "career"},
            {"ge": "ბეჭდვა", "en": "typing / printing", "ru": "печать / набор", "group": "skill"},
            {"ge": "პრეზენტაცია", "en": "presentation", "ru": "презентация", "group": "skill"},
            {"ge": "მომზადება", "en": "preparation", "ru": "подготовка", "group": "process"},
            {"ge": "მოვემზადოთ", "en": "let us prepare", "ru": "давайте подготовимся", "group": "grammar"},
            {"ge": "შეუძლია", "en": "he/she can", "ru": "может", "group": "grammar"},
            {"ge": "აქვს", "en": "he/she has", "ru": "имеет / у него есть", "group": "grammar"},
        ],
    },
    "4": {
        "title": "Unusual Professions",
        "grammar": {
            "en": "Profession nouns with -ობა suffix: პროფესია → პროფესიონალობა. Descriptive relative clauses: რომელიც... Reported speech in journalism: გაზეთის რეპორტიორი.",
            "ru": "Профессии с -ობა. Придаточные с რომელიც.",
            "example_ge": "ის მუშაობს ფერმაზე.",
            "example_en": "He/she works on a farm.",
        },
        "easier_than_russian": "Many profession words are international: ინჟინერი, რეპორტიორი, ფერმერი.",
        "vocab": [
            {"ge": "პროფესია", "en": "profession", "ru": "профессия", "group": "career"},
            {"ge": "უჩვეულო პროფესია", "en": "unusual profession", "ru": "необычная профессия", "group": "career"},
            {"ge": "ფერმა", "en": "farm", "ru": "ферма", "group": "workplace"},
            {"ge": "ფერმერი", "en": "farmer", "ru": "фермер", "group": "profession"},
            {"ge": "რანჩო", "en": "ranch", "ru": "ранчо", "group": "workplace"},
            {"ge": "სათბური", "en": "greenhouse", "ru": "теплица", "group": "workplace"},
            {"ge": "ინკუბატორი", "en": "incubator", "ru": "инкубатор", "group": "equipment"},
            {"ge": "რეპორტიორი", "en": "reporter", "ru": "репортер", "group": "profession"},
            {"ge": "გაზეთი", "en": "newspaper", "ru": "газета", "group": "media"},
            {"ge": "ფოტოგრაფი", "en": "photographer", "ru": "фотограф", "group": "profession"},
            {"ge": "ფეხბურთელი", "en": "footballer", "ru": "футболист", "group": "profession"},
            {"ge": "მწვრთნელი", "en": "coach / trainer", "ru": "тренер", "group": "profession"},
            {"ge": "მსაჯი", "en": "referee / judge", "ru": "судья / арбитр", "group": "profession"},
            {"ge": "მსახიობი", "en": "actor", "ru": "актер", "group": "profession"},
            {"ge": "მყვინთავი", "en": "diver", "ru": "дайвер", "group": "profession"},
            {"ge": "მეხანძრე", "en": "firefighter", "ru": "пожарный", "group": "profession"},
            {"ge": "სამუშაო ადგილი", "en": "workplace", "ru": "место работы", "group": "workplace"},
            {"ge": "სამუშაო გრაფიკი", "en": "work schedule", "ru": "график работы", "group": "employment"},
            {"ge": "მოვალეობა", "en": "duty", "ru": "обязанность", "group": "employment"},
            {"ge": "აღწერა", "en": "description", "ru": "описание", "group": "language"},
            {"ge": "ცნობილი", "en": "famous", "ru": "известный", "group": "adjective"},
            {"ge": "რომელიც", "en": "which / who", "ru": "который", "group": "grammar"},
        ],
    },
    "5": {
        "title": "Alpinism & Instructions",
        "grammar": {
            "en": "Conditional markings on maps: მწვერვალი (peak), ნაპრალი (canyon), ქვათაცვენა (rockfall zone). Imperative instructions: დაიცავით (observe!), არ გადაინაცვლოთ (don't move!).",
            "ru": "Альпинизм: მწვერვალი, ნაპრალი. Повелительное: დაიცავით.",
            "example_ge": "აქ საშიში ადგილია.",
            "example_en": "This is a dangerous place here.",
        },
        "easier_than_russian": "Mountain vocabulary is vivid compounds: ქვათაცვენა = stone-fall-place.",
        "vocab": [
            {"ge": "ალპინიზმი", "en": "alpinism / mountaineering", "ru": "альпинизм", "group": "sport"},
            {"ge": "მთა", "en": "mountain", "ru": "гора", "group": "terrain"},
            {"ge": "მწვერვალი", "en": "peak / summit", "ru": "вершина", "group": "terrain"},
            {"ge": "ბილიკი", "en": "trail", "ru": "тропа", "group": "terrain"},
            {"ge": "ნაპრალი", "en": "canyon / gorge", "ru": "ущелье", "group": "terrain"},
            {"ge": "ქვათაცვენა", "en": "rockfall zone", "ru": "камнепад", "group": "hazard"},
            {"ge": "მყინვარი", "en": "glacier", "ru": "ледник", "group": "terrain"},
            {"ge": "კლდე", "en": "cliff / rock", "ru": "скала", "group": "terrain"},
            {"ge": "თოკი", "en": "rope", "ru": "веревка", "group": "equipment"},
            {"ge": "კარაბინი", "en": "carabiner", "ru": "карабин", "group": "equipment"},
            {"ge": "ჩაფხუტი", "en": "helmet", "ru": "шлем", "group": "equipment"},
            {"ge": "რუკა", "en": "map", "ru": "карта", "group": "navigation"},
            {"ge": "პირობითი აღნიშვნა", "en": "conditional map marking", "ru": "условное обозначение", "group": "navigation"},
            {"ge": "სირთულის დონე", "en": "difficulty level", "ru": "уровень сложности", "group": "navigation"},
            {"ge": "სირტის გრადაცია", "en": "slope gradient", "ru": "уклон склона", "group": "navigation"},
            {"ge": "ინსტრუქცია", "en": "instruction", "ru": "инструкция", "group": "safety"},
            {"ge": "მიმართულება", "en": "direction", "ru": "направление", "group": "navigation"},
            {"ge": "მონაკვეთი", "en": "section / segment", "ru": "участок", "group": "navigation"},
            {"ge": "საშიში", "en": "dangerous", "ru": "опасный", "group": "safety"},
            {"ge": "ფრთხილად", "en": "carefully", "ru": "осторожно", "group": "safety"},
            {"ge": "დაიცავით", "en": "observe! / keep! (formal)", "ru": "соблюдайте!", "group": "grammar"},
            {"ge": "არ გადაინაცვლოთ", "en": "do not move", "ru": "не перемещайтесь", "group": "grammar"},
        ],
    },
    "6": {
        "title": "Sports & the Olympics",
        "grammar": {
            "en": "Past narrative: დაიწყო (began), გაიმარჯვა (won). Sports types: ექსტრემალური სპორტი. Purpose clauses: რათა (so that) — რათა თაყვანი ეცათ.",
            "ru": "Прошедшее: დაიწყო, გაიმარჯვა. Цель: რათა.",
            "example_ge": "ოლიმპიური თამაშები ოთხ წელიწადში ერთხელ იმართება.",
            "example_en": "The Olympic Games are held once every four years.",
        },
        "easier_than_russian": "Olympic vocabulary is international: ოლიმპიადა, მედალი, ჩემპიონი.",
        "vocab": [
            {"ge": "ოლიმპიადა", "en": "Olympics", "ru": "олимпиада", "group": "sport event"},
            {"ge": "ოლიმპიური თამაშები", "en": "Olympic Games", "ru": "олимпийские игры", "group": "sport event"},
            {"ge": "სპორტი", "en": "sport", "ru": "спорт", "group": "sport"},
            {"ge": "თამაში", "en": "game", "ru": "игра", "group": "sport"},
            {"ge": "ჩემპიონი", "en": "champion", "ru": "чемпион", "group": "result"},
            {"ge": "მედალი", "en": "medal", "ru": "медаль", "group": "result"},
            {"ge": "ოქროს მედალი", "en": "gold medal", "ru": "золотая медаль", "group": "result"},
            {"ge": "ვერცხლის მედალი", "en": "silver medal", "ru": "серебряная медаль", "group": "result"},
            {"ge": "ბრინჯაოს მედალი", "en": "bronze medal", "ru": "бронзовая медаль", "group": "result"},
            {"ge": "მონაწილე", "en": "participant", "ru": "участник", "group": "sport event"},
            {"ge": "გუნდი", "en": "team", "ru": "команда", "group": "sport"},
            {"ge": "შეჯიბრება", "en": "competition", "ru": "соревнование", "group": "sport event"},
            {"ge": "გამარჯვება", "en": "victory", "ru": "победа", "group": "result"},
            {"ge": "გაიმარჯვა", "en": "won / was victorious", "ru": "победил", "group": "grammar"},
            {"ge": "დაიწყო", "en": "began", "ru": "начался", "group": "grammar"},
            {"ge": "დასრულდა", "en": "finished", "ru": "закончился", "group": "grammar"},
            {"ge": "მწვრთნელი", "en": "coach", "ru": "тренер", "group": "sport"},
            {"ge": "რეკორდი", "en": "record", "ru": "рекорд", "group": "result"},
            {"ge": "რიტუალი", "en": "ritual", "ru": "ритуал", "group": "history"},
            {"ge": "მსხვერპლი", "en": "sacrifice / offering", "ru": "жертва", "group": "history"},
            {"ge": "ექსტრემალური სპორტი", "en": "extreme sport", "ru": "экстремальный спорт", "group": "sport"},
            {"ge": "ჯომარდობა", "en": "rafting / kayaking", "ru": "гребля / рафтинг", "group": "sport"},
        ],
    },
    "7": {
        "title": "Free Time & Music",
        "grammar": {
            "en": "Free time: თავისუფალი დრო, როგორ ატარებ? Music verbs: მოსმენა (listening), კონცერტი. Suggestions: კარგი იქნებოდა თუ... (it would be good if...).",
            "ru": "Досуг: თავისუფალი დრო. Музыка: მოსმენა, კონცერტი.",
            "example_ge": "თავისუფალ დროს მუსიკას ვუსმენ.",
            "example_en": "In my free time I listen to music.",
        },
        "easier_than_russian": "Music loanwords: კონცერტი, ორკესტრი, მელოდია.",
        "vocab": [
            {"ge": "თავისუფალი დრო", "en": "free time", "ru": "свободное время", "group": "lifestyle"},
            {"ge": "ჰობი", "en": "hobby", "ru": "хобби", "group": "lifestyle"},
            {"ge": "მუსიკა", "en": "music", "ru": "музыка", "group": "music"},
            {"ge": "მუსიკოსი", "en": "musician", "ru": "музыкант", "group": "music"},
            {"ge": "კონცერტი", "en": "concert", "ru": "концерт", "group": "music"},
            {"ge": "მელოდია", "en": "melody", "ru": "мелодия", "group": "music"},
            {"ge": "სიმღერა", "en": "song", "ru": "песня", "group": "music"},
            {"ge": "ორკესტრი", "en": "orchestra", "ru": "оркестр", "group": "music"},
            {"ge": "ფესტივალი", "en": "festival", "ru": "фестиваль", "group": "event"},
            {"ge": "ღონისძიება", "en": "event", "ru": "мероприятие", "group": "event"},
            {"ge": "დასვენება", "en": "rest / relaxation", "ru": "отдых", "group": "lifestyle"},
            {"ge": "გართობა", "en": "entertainment / fun", "ru": "развлечение", "group": "lifestyle"},
            {"ge": "კითხვა", "en": "reading", "ru": "чтение", "group": "activity"},
            {"ge": "წიგნი", "en": "book", "ru": "книга", "group": "activity"},
            {"ge": "კითხვის კლუბი", "en": "book club", "ru": "книжный клуб", "group": "activity"},
            {"ge": "კინო", "en": "cinema", "ru": "кино", "group": "activity"},
            {"ge": "თეატრი", "en": "theater", "ru": "театр", "group": "activity"},
            {"ge": "მეგობრები", "en": "friends", "ru": "друзья", "group": "social"},
            {"ge": "მოგზაურობა", "en": "travel", "ru": "путешествие", "group": "activity"},
            {"ge": "მოსმენა", "en": "listening", "ru": "слушание", "group": "grammar"},
            {"ge": "ვატარებ", "en": "I spend (time)", "ru": "провожу (время)", "group": "grammar"},
            {"ge": "მომწონს", "en": "I like", "ru": "мне нравится", "group": "grammar"},
        ],
    },
    "8": {
        "title": "Flash Mob & Social Phenomena",
        "grammar": {
            "en": "Relative clauses with რომელიც (which/who) — agrees in number. Connecting sentences: მაკავშირებელი სიტყვა. Flash mob as social phenomenon vocabulary.",
            "ru": "Придаточные с რომელიც. Связующие слова.",
            "example_ge": "ფლეშმობი, რომელიც ქუჩაში ჩანს, გართობისთვისაა.",
            "example_en": "The flash mob that appears in the street is for fun.",
        },
        "easier_than_russian": "ფლეშმობი is a direct loan — same word, Georgian plural ending.",
        "vocab": [
            {"ge": "ფლეშმობი", "en": "flash mob", "ru": "флешмоб", "group": "social event"},
            {"ge": "სოციალური ფენომენი", "en": "social phenomenon", "ru": "социальный феномен", "group": "concept"},
            {"ge": "მონაწილეობა", "en": "participation", "ru": "участие", "group": "social event"},
            {"ge": "მონაწილე", "en": "participant", "ru": "участник", "group": "social event"},
            {"ge": "ორგანიზატორი", "en": "organizer", "ru": "организатор", "group": "social event"},
            {"ge": "რეკლამა", "en": "advertisement", "ru": "реклама", "group": "media"},
            {"ge": "კამპანია", "en": "campaign", "ru": "кампания", "group": "media"},
            {"ge": "ქუჩა", "en": "street", "ru": "улица", "group": "place"},
            {"ge": "მოედანი", "en": "square", "ru": "площадь", "group": "place"},
            {"ge": "ფეხით მოსიარულე", "en": "pedestrian", "ru": "пешеход", "group": "people"},
            {"ge": "გამვლელი", "en": "passerby", "ru": "прохожий", "group": "people"},
            {"ge": "ცეკვა", "en": "dance", "ru": "танец", "group": "activity"},
            {"ge": "სიმღერა", "en": "song", "ru": "песня", "group": "activity"},
            {"ge": "ვიდეოჩანაწერი", "en": "video recording", "ru": "видеозапись", "group": "media"},
            {"ge": "წინასწარ", "en": "in advance / beforehand", "ru": "заранее", "group": "time"},
            {"ge": "შეტყობინება", "en": "notification", "ru": "уведомление", "group": "communication"},
            {"ge": "გაფრთხილება", "en": "warning", "ru": "предупреждение", "group": "communication"},
            {"ge": "შეშინება", "en": "frightening / scare", "ru": "испуг", "group": "emotion"},
            {"ge": "ემოცია", "en": "emotion", "ru": "эмоция", "group": "emotion"},
            {"ge": "რომელიც", "en": "which / who", "ru": "который", "group": "grammar"},
            {"ge": "მაკავშირებელი სიტყვა", "en": "linking word", "ru": "связующее слово", "group": "grammar"},
            {"ge": "საზოგადოება", "en": "society", "ru": "общество", "group": "concept"},
        ],
    },
    "9": {
        "title": "Online Shopping",
        "grammar": {
            "en": "Future tense: მომავალი დრო. Modal particle უნდა for advice/instructions in shopping context. Onomatopoeia: ონეომანია. Imperative: წართქმითი და უკუთქმითი ბრძანებითი.",
            "ru": "Будущее время. უნდა в контексте покупок. Ономатопея: ონეომანია.",
            "example_ge": "ონლაინ შეგიძლიათ განვადებით იყიდოთ.",
            "example_en": "You can buy online in installments.",
        },
        "easier_than_russian": "E-commerce terms are international: ონლაინშოპინგი, განვადება, ბანკომატი.",
        "vocab": [
            {"ge": "ონლაინვაჭრობა", "en": "online shopping", "ru": "онлайн-торговля", "group": "e-commerce"},
            {"ge": "ონლაინმაღაზია", "en": "online store", "ru": "интернет-магазин", "group": "e-commerce"},
            {"ge": "შეკვეთა", "en": "order", "ru": "заказ", "group": "order flow"},
            {"ge": "შეკვეთის გაფორმება", "en": "placing an order", "ru": "оформление заказа", "group": "order flow"},
            {"ge": "მიწოდება", "en": "delivery", "ru": "доставка", "group": "order flow"},
            {"ge": "მისამართი", "en": "address", "ru": "адрес", "group": "order flow"},
            {"ge": "გადახდა", "en": "payment", "ru": "оплата", "group": "payment"},
            {"ge": "საბანკო ბარათი", "en": "bank card", "ru": "банковская карта", "group": "payment"},
            {"ge": "განვადება", "en": "installment plan", "ru": "рассрочка", "group": "payment"},
            {"ge": "საბანკო განვადება", "en": "bank installment", "ru": "банковская рассрочка", "group": "payment"},
            {"ge": "ფასდაკლება", "en": "discount", "ru": "скидка", "group": "sales"},
            {"ge": "აქცია", "en": "special offer / promo", "ru": "акция", "group": "sales"},
            {"ge": "დაბრუნება", "en": "return", "ru": "возврат", "group": "consumer rights"},
            {"ge": "გარანტია", "en": "warranty", "ru": "гарантия", "group": "consumer rights"},
            {"ge": "ტექნიკა", "en": "electronics / equipment", "ru": "техника", "group": "products"},
            {"ge": "პროდუქტი", "en": "product", "ru": "продукт / товар", "group": "products"},
            {"ge": "კალათა", "en": "cart / basket", "ru": "корзина", "group": "order flow"},
            {"ge": "ონეომანია", "en": "oniomania / shopping addiction", "ru": "ониомания", "group": "concept"},
            {"ge": "მომავალი დრო", "en": "future tense", "ru": "будущее время", "group": "grammar"},
            {"ge": "უნდა", "en": "should / must", "ru": "должен / нужно", "group": "grammar"},
            {"ge": "იყიდება", "en": "is sold", "ru": "продается", "group": "grammar"},
            {"ge": "მომხმარებელი", "en": "consumer / customer", "ru": "покупатель", "group": "people"},
        ],
    },
    "10": {
        "title": "Taxes & Consumer Rights",
        "grammar": {
            "en": "Complaint letter vocabulary. Direct/indirect imperative. Subject case with -ენიანი participles. Compound words: ორცნებიანი კომპოზიტები.",
            "ru": "Жалоба: საჩივარი. Повелительное прямое/косвенное. Сложные слова.",
            "example_ge": "საჩივარი უნდა დაწეროთ ოფიციალურ ენაზე.",
            "example_en": "The complaint must be written in official language.",
        },
        "easier_than_russian": "Consumer rights terms mirror EU-style vocabulary — familiar concepts.",
        "vocab": [
            {"ge": "გადასახადი", "en": "tax", "ru": "налог", "group": "finance"},
            {"ge": "გადასახადის გადახდა", "en": "tax payment", "ru": "уплата налога", "group": "finance"},
            {"ge": "დეკლარაცია", "en": "declaration", "ru": "декларация", "group": "document"},
            {"ge": "სახელმწიფო ბიუჯეტი", "en": "state budget", "ru": "государственный бюджет", "group": "finance"},
            {"ge": "საჩივარი", "en": "complaint", "ru": "жалоба", "group": "document"},
            {"ge": "განცხადება", "en": "statement / application", "ru": "заявление", "group": "document"},
            {"ge": "მომხმარებელი", "en": "consumer", "ru": "потребитель", "group": "people"},
            {"ge": "მომხმარებლის უფლება", "en": "consumer right", "ru": "право потребителя", "group": "law"},
            {"ge": "დაცვა", "en": "protection", "ru": "защита", "group": "law"},
            {"ge": "კანონი", "en": "law", "ru": "закон", "group": "law"},
            {"ge": "კონტრაქტი", "en": "contract", "ru": "контракт", "group": "document"},
            {"ge": "ქვითარი", "en": "receipt", "ru": "квитанция", "group": "document"},
            {"ge": "ჩეკი", "en": "receipt check", "ru": "чек", "group": "document"},
            {"ge": "მომსახურება", "en": "service", "ru": "услуга", "group": "consumer rights"},
            {"ge": "ხარისხი", "en": "quality", "ru": "качество", "group": "consumer rights"},
            {"ge": "ბაზარი", "en": "market", "ru": "рынок", "group": "economy"},
            {"ge": "ფასი", "en": "price", "ru": "цена", "group": "economy"},
            {"ge": "ინტერნეტმაღაზია", "en": "online store", "ru": "интернет-магазин", "group": "economy"},
            {"ge": "ოფიციალური ენა", "en": "official language", "ru": "официальный язык", "group": "writing"},
            {"ge": "დაბრუნება", "en": "return", "ru": "возврат", "group": "consumer rights"},
            {"ge": "ანაზღაურება", "en": "compensation / reimbursement", "ru": "компенсация", "group": "consumer rights"},
            {"ge": "ზედამხედველობა", "en": "supervision / oversight", "ru": "надзор", "group": "law"},
        ],
    },
    "11": {
        "title": "Regional Georgian Cuisine",
        "grammar": {
            "en": "Regional food descriptions: სვანური, იმერული, კახური. Hospitality dialogue: სტუმარმასპინძლობა. Recipe language: ინგრედიენტი, მომზადება.",
            "ru": "Региональная кухня: სვანური, კახური. Гостеприимство: სტუმარმასპინძლობა.",
            "example_ge": "სვანეთში ტრადიციული კერძი ჩურჩხელაა.",
            "example_en": "In Svaneti the traditional dish is churchkhela.",
        },
        "easier_than_russian": "Georgian food names are the same in every language — learn once, use forever.",
        "vocab": [
            {"ge": "კულინარია", "en": "cuisine", "ru": "кулинария", "group": "food"},
            {"ge": "კერძი", "en": "dish", "ru": "блюдо", "group": "food"},
            {"ge": "რეცეპტი", "en": "recipe", "ru": "рецепт", "group": "cooking"},
            {"ge": "ინგრედიენტი", "en": "ingredient", "ru": "ингредиент", "group": "cooking"},
            {"ge": "მომზადება", "en": "preparation / cooking", "ru": "приготовление", "group": "cooking"},
            {"ge": "სვანური", "en": "Svan (regional)", "ru": "сванский", "group": "region"},
            {"ge": "იმერული", "en": "Imeretian (regional)", "ru": "имеретинский", "group": "region"},
            {"ge": "კახური", "en": "Kakhetian (regional)", "ru": "кахетинский", "group": "region"},
            {"ge": "ჩიხირთმა", "en": "chikhirtma soup", "ru": "чихиртма", "group": "dish"},
            {"ge": "ბოჟბა", "en": "bozbashi soup", "ru": "божбаши", "group": "dish"},
            {"ge": "ხაჭაპური", "en": "khachapuri", "ru": "хачапури", "group": "dish"},
            {"ge": "ხინკალი", "en": "khinkali", "ru": "хинкали", "group": "dish"},
            {"ge": "ჩურჩხელა", "en": "churchkhela", "ru": "чурчхела", "group": "dish"},
            {"ge": "სანელებელი", "en": "spice", "ru": "специя", "group": "ingredient"},
            {"ge": "მარილი", "en": "salt", "ru": "соль", "group": "ingredient"},
            {"ge": "წიწაკა", "en": "pepper", "ru": "перец", "group": "ingredient"},
            {"ge": "რესტორანი", "en": "restaurant", "ru": "ресторан", "group": "place"},
            {"ge": "მენიუ", "en": "menu", "ru": "меню", "group": "place"},
            {"ge": "სტუმარმასპინძლობა", "en": "hospitality", "ru": "гостеприимство", "group": "culture"},
            {"ge": "ტრადიციული", "en": "traditional", "ru": "традиционный", "group": "culture"},
            {"ge": "გემრიელი", "en": "tasty / delicious", "ru": "вкусный", "group": "adjective"},
            {"ge": "კვების ობიექტი", "en": "food establishment", "ru": "заведение питания", "group": "place"},
        ],
    },
    "12": {
        "title": "Healthy Living & the Caucasus",
        "grammar": {
            "en": "Diet & health: ჯანსაღი ცხოვრების წესი, დიეტა. Argumentation: საკუთარი აზრის არგუმენტირება. Geographic names: კავკასია, კავკასიელი. Dialect note: დიალექტური ფორმები.",
            "ru": "Здоровье: ჯანსაღი ცხოვრება, დიეტა. География: კავკასია.",
            "example_ge": "ჯანსაღი კვება ძალიან მნიშვნელოვანია.",
            "example_en": "Healthy eating is very important.",
        },
        "easier_than_russian": "Caucasus geography uses clear suffixes: კავკასიელი (Caucasian person), -ელი for nationality.",
        "vocab": [
            {"ge": "ჯანსაღი", "en": "healthy", "ru": "здоровый", "group": "health"},
            {"ge": "ჯანსაღი ცხოვრების წესი", "en": "healthy lifestyle", "ru": "здоровый образ жизни", "group": "health"},
            {"ge": "დიეტა", "en": "diet", "ru": "диета", "group": "health"},
            {"ge": "დაბალანსებული კვება", "en": "balanced nutrition", "ru": "сбалансированное питание", "group": "nutrition"},
            {"ge": "ვიტამინი", "en": "vitamin", "ru": "витамин", "group": "nutrition"},
            {"ge": "მინერალი", "en": "mineral", "ru": "минерал", "group": "nutrition"},
            {"ge": "წონა", "en": "weight", "ru": "вес", "group": "health"},
            {"ge": "კალორია", "en": "calorie", "ru": "калория", "group": "nutrition"},
            {"ge": "სწრაფი კვება", "en": "fast food", "ru": "фастфуд", "group": "nutrition"},
            {"ge": "სასარგებლო", "en": "beneficial / healthy", "ru": "полезный", "group": "health"},
            {"ge": "მავნე", "en": "harmful", "ru": "вредный", "group": "health"},
            {"ge": "ვარჯიში", "en": "exercise", "ru": "упражнение", "group": "health"},
            {"ge": "სეირნობა", "en": "walking", "ru": "прогулка", "group": "health"},
            {"ge": "ძილი", "en": "sleep", "ru": "сон", "group": "health"},
            {"ge": "რეკომენდაცია", "en": "recommendation", "ru": "рекомендация", "group": "communication"},
            {"ge": "არგუმენტაცია", "en": "argumentation", "ru": "аргументация", "group": "communication"},
            {"ge": "კავკასია", "en": "Caucasus", "ru": "Кавказ", "group": "geography"},
            {"ge": "კავკასიელი", "en": "Caucasian (person)", "ru": "кавказец", "group": "geography"},
            {"ge": "ქისტი", "en": "Kist", "ru": "кистинец", "group": "ethnography"},
            {"ge": "გეოგრაფიული", "en": "geographical", "ru": "географический", "group": "geography"},
            {"ge": "მდებარეობა", "en": "location", "ru": "расположение", "group": "geography"},
            {"ge": "დიალექტი", "en": "dialect", "ru": "диалект", "group": "language"},
        ],
    },
}


def main():
    with open(LESSON_DATA, encoding="utf-8") as f:
        data = json.load(f)

    data["b1"] = B1

    with open(LESSON_DATA, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"✅ Added B1 with {len(B1)} lessons to {LESSON_DATA}")
    print("B1 vocab counts per lesson:")
    for lesson_id in sorted(B1, key=int):
        count = len(B1[lesson_id]["vocab"])
        print(f"  Lesson {lesson_id}: {count} words")


if __name__ == "__main__":
    main()
