#!/usr/bin/env python3
"""Merge full A1 აღმართი lessons into lesson_data.json. Run: python3 build_a1_lessons.py"""

import json

from config import LESSON_DATA

A1 = {
    "1": {
        "title": "Alphabet (intro)",
        "grammar": {
            "en": "აი = here is / look. ეს არის X = this is X. ეს არ არის X = this is not X. Short form: nouns ending in -ი drop არის → just add -ა (კაფეა = it's a café).",
            "ru": "აი ≈ «вот». ეს არის = «это есть». ეს არ არის = «это не». Краткая форма: после существительного на -ი вместо «არის» просто -ა (как у нас «это кафе» → კაფეა).",
            "example_ge": "აი კაფე. ეს კაფეა.",
            "example_en": "Here is a café. This is a café.",
            "bullets": [
                "აი + noun = here is / look at…",
                "ეს არის X = this is X",
                "ეს არ არის X = this is not X",
                "Short form: კაფეა, ოფისია (= it is a café / office)",
                "Georgian has 33 letters — 5 vowels, 28 consonants",
            ],
        },
        "easier_than_russian": "No gender on nouns — კაფე is just კაფე, no masculine/feminine endings.",
        "phrases": [
            {"ge": "აი ტელეფონი.", "en": "Here is a phone.", "ru": "Вот телефон."},
            {"ge": "ეს კაფეა.", "en": "This is a café.", "ru": "Это кафе."},
            {"ge": "ეს არ არის ოფისი.", "en": "This is not an office.", "ru": "Это не офис."},
            {"ge": "აი სტუდენტი.", "en": "Here is a student.", "ru": "Вот студент."},
        ],
        "vocab": [
            {"ge": "ოფისი", "en": "office", "ru": "офис", "group": "Loanwords"},
            {"ge": "ტელეფონი", "en": "phone", "ru": "телефон", "group": "Loanwords"},
            {"ge": "კომპიუტერი", "en": "computer", "ru": "компьютер", "group": "Loanwords"},
            {"ge": "ფოტო", "en": "photo", "ru": "фото", "group": "Loanwords"},
            {"ge": "პრინტერი", "en": "printer", "ru": "принтер", "group": "Loanwords"},
            {"ge": "ლამპა", "en": "lamp", "ru": "лампа", "group": "Loanwords"},
            {"ge": "პასპორტი", "en": "passport", "ru": "паспорт", "group": "Loanwords"},
            {"ge": "კაფე", "en": "café", "ru": "кафе", "group": "Loanwords"},
            {"ge": "სუპერმარკეტი", "en": "supermarket", "ru": "супермаркет", "group": "Loanwords"},
            {"ge": "აეროპორტი", "en": "airport", "ru": "аэропорт", "group": "Loanwords"},
            {"ge": "ოპერა", "en": "opera", "ru": "опера", "group": "Loanwords"},
            {"ge": "ტურისტი", "en": "tourist", "ru": "турист", "group": "Loanwords"},
            {"ge": "სტუდენტი", "en": "student", "ru": "студент", "group": "Loanwords"},
            {"ge": "ეს", "en": "this", "ru": "это", "group": "Core words"},
            {"ge": "არის", "en": "is / there is", "ru": "есть / является", "group": "Core words"},
            {"ge": "არა", "en": "not / no", "ru": "не / нет", "group": "Core words"},
            {"ge": "აი", "en": "here is / look", "ru": "вот", "group": "Core words"},
        ],
    },
    "2": {
        "title": "Greetings + Alphabet",
        "grammar": {
            "en": "Questions = rising intonation. ვინ? = who, რა? = what, სად? = where. Identity: ეს ნინოა? — დიახ/არა.",
            "ru": "Вопрос = интонация вверх. ვინ? = «кто?», რა? = «что?», სად? = «где?». Идентификация: «это Нино?» → ეს ნინოა?",
            "example_ge": "გამარჯობა! ეს ნინოა?",
            "example_en": "Hello! Is this Nino?",
            "bullets": [
                "Yes/no questions often need only rising intonation",
                "ეს ნინოა? = Is this Nino?",
                "დიახ = yes · არა = no",
                "გაგიმარჯოს = informal reply to გამარჯობა",
            ],
        },
        "easier_than_russian": "No «ты/вы» verb conjugation in greetings — გამარჯობა works for everyone.",
        "phrases": [
            {"ge": "გამარჯობა! როგორ ხარ?", "en": "Hello! How are you?", "ru": "Здравствуй! Как дела?"},
            {"ge": "კარგად, გმადლობ.", "en": "Fine, thank you.", "ru": "Хорошо, спасибо."},
            {"ge": "რა გქვია?", "en": "What's your name?", "ru": "Как тебя зовут?"},
            {"ge": "მე მქვია ნინო.", "en": "My name is Nino.", "ru": "Меня зовут Нино."},
            {"ge": "სად ხარ?", "en": "Where are you?", "ru": "Где ты?"},
            {"ge": "ვერ გავიგე. გაიმეორე, გთხოვ.", "en": "I didn't understand. Please repeat.", "ru": "Я не понял(а). Повтори, пожалуйста."},
        ],
        "vocab": [
            {"ge": "გამარჯობა", "en": "hello", "ru": "здравствуйте", "group": "Greetings"},
            {"ge": "გამარჯობათ", "en": "hello (formal)", "ru": "здравствуйте (уваж.)", "group": "Greetings"},
            {"ge": "გაგიმარჯოს", "en": "hi (response)", "ru": "и тебе привет", "group": "Greetings"},
            {"ge": "ნახვამდის", "en": "goodbye", "ru": "до свидания", "group": "Greetings"},
            {"ge": "დიახ", "en": "yes", "ru": "да", "group": "Greetings"},
            {"ge": "არა", "en": "no", "ru": "нет", "group": "Greetings"},
            {"ge": "ბატონი", "en": "Mr / sir", "ru": "господин", "group": "Titles"},
            {"ge": "ქალბატონი", "en": "Ms / madam", "ru": "госпожа", "group": "Titles"},
            {"ge": "ვინ", "en": "who", "ru": "кто", "group": "Questions"},
            {"ge": "რა", "en": "what", "ru": "что", "group": "Questions"},
            {"ge": "სად", "en": "where", "ru": "где", "group": "Questions"},
            {"ge": "თბილისი", "en": "Tbilisi", "ru": "Тбилиси", "group": "Places"},
            {"ge": "საქართველო", "en": "Georgia (country)", "ru": "Грузия", "group": "Places"},
            {"ge": "ევროპა", "en": "Europe", "ru": "Европа", "group": "Places"},
            {"ge": "აზია", "en": "Asia", "ru": "Азия", "group": "Places"},
            {"ge": "ამერიკა", "en": "America", "ru": "Америка", "group": "Places"},
            {"ge": "ქვეყანა", "en": "country", "ru": "страна", "group": "Places"},
            {"ge": "ქალაქი", "en": "city", "ru": "город", "group": "Places"},
            {"ge": "კონტინენტი", "en": "continent", "ru": "континент", "group": "Places"},
            {"ge": "როგორ ხარ", "en": "how are you?", "ru": "как дела?", "group": "Useful phrases"},
            {"ge": "კარგად", "en": "fine / well", "ru": "хорошо", "group": "Useful phrases"},
            {"ge": "გმადლობ", "en": "thank you", "ru": "спасибо", "group": "Useful phrases"},
            {"ge": "რა გქვია", "en": "what is your name?", "ru": "как тебя зовут?", "group": "Useful phrases"},
            {"ge": "მე მქვია", "en": "my name is", "ru": "меня зовут", "group": "Useful phrases"},
        ],
    },
    "3": {
        "title": "Food & Drink I",
        "grammar": {
            "en": "Negative with არ before the verb. Mass nouns have no plural (like Russian «чай», «молоко»). მინდა = I want.",
            "ru": "Отрицание: არ перед глаголом (как «не»). Нарицательные без множественного числа — как в русском «чай», «молоко». მინდა = «я хочу».",
            "example_ge": "არ მინდა ღვინო. მინდა ყავა.",
            "example_en": "I don't want wine. I want coffee.",
            "bullets": [
                "არ + verb = negation",
                "Food/drink words usually have no plural at A1",
                "მინდა ყავა = I want coffee (just name the item)",
            ],
        },
        "easier_than_russian": "No case changes on food words when ordering — just say the word.",
        "phrases": [
            {"ge": "მინდა ყავა, გთხოვ.", "en": "I'd like coffee, please.", "ru": "Я хочу кофе, пожалуйста."},
            {"ge": "არ მინდა ლუდი.", "en": "I don't want beer.", "ru": "Я не хочу пиво."},
            {"ge": "ერთი ხაჭაპური, გთხოვ.", "en": "One khachapuri, please.", "ru": "Один хачапури, пожалуйста."},
            {"ge": "რა გინდა?", "en": "What do you want?", "ru": "Что ты хочешь?"},
        ],
        "vocab": [
            {"ge": "ყავა", "en": "coffee", "ru": "кофе", "group": "Drinks"},
            {"ge": "ჩაი", "en": "tea", "ru": "чай", "group": "Drinks"},
            {"ge": "წყალი", "en": "water", "ru": "вода", "group": "Drinks"},
            {"ge": "ღვინო", "en": "wine", "ru": "вино", "group": "Drinks"},
            {"ge": "ლუდი", "en": "beer", "ru": "пиво", "group": "Drinks"},
            {"ge": "წვენი", "en": "juice", "ru": "сок", "group": "Drinks"},
            {"ge": "რძე", "en": "milk", "ru": "молоко", "group": "Drinks"},
            {"ge": "პური", "en": "bread", "ru": "хлеб", "group": "Food"},
            {"ge": "ხაჭაპური", "en": "cheese bread (khachapuri)", "ru": "хачапури", "group": "Food"},
            {"ge": "ხინკალი", "en": "dumplings (khinkali)", "ru": "хинкали", "group": "Food"},
            {"ge": "სალათა", "en": "salad", "ru": "салат", "group": "Food"},
            {"ge": "საჭმელი", "en": "food", "ru": "еда", "group": "Food"},
            {"ge": "სასმელი", "en": "drink / beverage", "ru": "напиток", "group": "Food"},
            {"ge": "ვაშლი", "en": "apple", "ru": "яблоко", "group": "Fruit"},
            {"ge": "ლიმონი", "en": "lemon", "ru": "лимон", "group": "Fruit"},
            {"ge": "მენიუ", "en": "menu", "ru": "меню", "group": "At the café"},
            {"ge": "მინდა", "en": "I want", "ru": "я хочу", "group": "At the café"},
            {"ge": "არ მინდა", "en": "I don't want", "ru": "я не хочу", "group": "At the café"},
            {"ge": "გთხოვ", "en": "please", "ru": "пожалуйста", "group": "At the café"},
            {"ge": "ერთი", "en": "one / a", "ru": "один / один", "group": "At the café"},
            {"ge": "ბორჯომი", "en": "pear", "ru": "груша", "group": "Fruit"},
            {"ge": "ყველი", "en": "plum", "ru": "слива", "group": "Fruit"},
        ],
    },
    "4": {
        "title": "Food & Drink II + Professions",
        "grammar": {
            "en": "ვარ/ხარ/არის/ვართ/ხართ/არიან = to be (all persons). Plural: add -ები. აქ = here, იქ = there.",
            "ru": "Глагол «быть»: ვარ (я), ხარ (ты), არის (он/она), ვართ (мы), ხართ (вы), არიან (они). Мн.ч.: -ები. აქ = здесь, იქ = там.",
            "example_ge": "აქ არის ექიმი. იქ არიან სტუდენტები.",
            "example_en": "Here is a doctor. There are students.",
            "bullets": [
                "ვარ · ხარ · არის · ვართ · ხართ · არიან",
                "Plural: add -ები (სტუდენტი → სტუდენტები)",
                "აქ = here · იქ = there · სად? = where? · რამდენი? = how many?",
            ],
        },
        "easier_than_russian": "Plural is just -ები on everything — no gendered plural forms.",
        "phrases": [
            {"ge": "აქ არის ექიმი.", "en": "Here is a doctor.", "ru": "Здесь врач."},
            {"ge": "იქ არიან სტუდენტები.", "en": "There are students.", "ru": "Там студенты."},
            {"ge": "სად არის ბანკი?", "en": "Where is the bank?", "ru": "Где банк?"},
            {"ge": "რამდენი სტუდენტია?", "en": "How many students are there?", "ru": "Сколько студентов?"},
        ],
        "vocab": [
            {"ge": "ექიმი", "en": "doctor", "ru": "врач", "group": "Professions"},
            {"ge": "მასწავლებელი", "en": "teacher", "ru": "учитель", "group": "Professions"},
            {"ge": "იურისტი", "en": "lawyer", "ru": "юрист", "group": "Professions"},
            {"ge": "ინჟინერი", "en": "engineer", "ru": "инженер", "group": "Professions"},
            {"ge": "ჟურნალისტი", "en": "journalist", "ru": "журналист", "group": "Professions"},
            {"ge": "მენეჯერი", "en": "manager", "ru": "менеджер", "group": "Professions"},
            {"ge": "სტუდენტი", "en": "student", "ru": "студент", "group": "Professions"},
            {"ge": "პროფესორი", "en": "professor", "ru": "профессор", "group": "Professions"},
            {"ge": "ერთი", "en": "one", "ru": "один", "group": "Numbers 1–10"},
            {"ge": "ორი", "en": "two", "ru": "два", "group": "Numbers 1–10"},
            {"ge": "სამი", "en": "three", "ru": "три", "group": "Numbers 1–10"},
            {"ge": "ოთხი", "en": "four", "ru": "четыре", "group": "Numbers 1–10"},
            {"ge": "ხუთი", "en": "five", "ru": "пять", "group": "Numbers 1–10"},
            {"ge": "ექვსი", "en": "six", "ru": "шесть", "group": "Numbers 1–10"},
            {"ge": "შვიდი", "en": "seven", "ru": "семь", "group": "Numbers 1–10"},
            {"ge": "რვა", "en": "eight", "ru": "восемь", "group": "Numbers 1–10"},
            {"ge": "ცხრა", "en": "nine", "ru": "девять", "group": "Numbers 1–10"},
            {"ge": "ათი", "en": "ten", "ru": "десять", "group": "Numbers 1–10"},
            {"ge": "აქ", "en": "here", "ru": "здесь", "group": "Place words"},
            {"ge": "იქ", "en": "there", "ru": "там", "group": "Place words"},
            {"ge": "რამდენი", "en": "how many", "ru": "сколько", "group": "Questions"},
            {"ge": "ვარ", "en": "I am", "ru": "я есть", "group": "To be"},
            {"ge": "ხარ", "en": "you are", "ru": "ты есть", "group": "To be"},
            {"ge": "არის", "en": "he/she/it is", "ru": "он/она есть", "group": "To be"},
            {"ge": "ვართ", "en": "we are", "ru": "мы есть", "group": "To be"},
            {"ge": "ხართ", "en": "you are (plural)", "ru": "вы есть", "group": "To be"},
            {"ge": "არიან", "en": "they are", "ru": "они есть", "group": "To be"},
            {"ge": "სად", "en": "where", "ru": "где", "group": "Questions"},
            {"ge": "სტუდენტები", "en": "students", "ru": "студенты", "group": "Plural examples"},
        ],
    },
    "5": {
        "title": "Family",
        "grammar": {
            "en": "Possessives: ჩემი/შენი/მისი/ჩვენი/თქვენი/მათი. Names: vowel ending +ს (ანას), consonant +ის (გიორგის). Age: X წლის ვარ.",
            "ru": "Притяжательные: ჩემი (мой), შენი (твой), მისი (его/её), ჩვენი (наш), თქვენი (ваш), მათი (их). Род. падеж имён: на гласную +ს, на согласную +ის.",
            "example_ge": "ეს ჩემი დედაა. ანის ფოტო.",
            "example_en": "This is my mother. Ana's photo.",
            "bullets": [
                "ჩემი · შენი · მისი · ჩვენი · თქვენი · მათი",
                "ანას ფოტო = Ana's photo (vowel name +ს)",
                "გიორგის ფოტო = Giorgi's photo (consonant +ის)",
                "X წლის ვარ = I am X years old",
            ],
        },
        "easier_than_russian": "მისი covers both his AND her — no gender on possessives!",
        "phrases": [
            {"ge": "ეს ჩემი დედაა.", "en": "This is my mother.", "ru": "Это моя мама."},
            {"ge": "ვისი ეს ფოტოა?", "en": "Whose photo is this?", "ru": "Чьё это фото?"},
            {"ge": "ოცი წლის ვარ.", "en": "I am twenty years old.", "ru": "Мне двадцать лет."},
            {"ge": "ანის ფოტო ძალიან ლამაზია.", "en": "Ana's photo is very beautiful.", "ru": "Фото Аны очень красивое."},
        ],
        "vocab": [
            {"ge": "დედა", "en": "mother", "ru": "мама", "group": "Family"},
            {"ge": "მამა", "en": "father", "ru": "папа", "group": "Family"},
            {"ge": "და", "en": "sister", "ru": "сестра", "group": "Family"},
            {"ge": "ძმა", "en": "brother", "ru": "брат", "group": "Family"},
            {"ge": "შვილი", "en": "child", "ru": "ребёнок", "group": "Family"},
            {"ge": "ვაჟი", "en": "son", "ru": "сын", "group": "Family"},
            {"ge": "გოგო", "en": "girl / daughter", "ru": "девочка / дочь", "group": "Family"},
            {"ge": "ბებია", "en": "grandmother", "ru": "бабушка", "group": "Family"},
            {"ge": "ბაბუა", "en": "grandfather", "ru": "дедушка", "group": "Family"},
            {"ge": "შვილიშვილი", "en": "grandchild", "ru": "внук / внучка", "group": "Family"},
            {"ge": "ქმარი", "en": "husband", "ru": "муж", "group": "Family"},
            {"ge": "ცოლი", "en": "wife", "ru": "жена", "group": "Family"},
            {"ge": "მეგობარი", "en": "friend", "ru": "друг", "group": "Family"},
            {"ge": "ოჯახი", "en": "family", "ru": "семья", "group": "Family"},
            {"ge": "ჩემი", "en": "my", "ru": "мой", "group": "Possessives"},
            {"ge": "შენი", "en": "your", "ru": "твой", "group": "Possessives"},
            {"ge": "მისი", "en": "his / her", "ru": "его / её", "group": "Possessives"},
            {"ge": "ჩვენი", "en": "our", "ru": "наш", "group": "Possessives"},
            {"ge": "თქვენი", "en": "your (plural)", "ru": "ваш", "group": "Possessives"},
            {"ge": "მათი", "en": "their", "ru": "их", "group": "Possessives"},
            {"ge": "ვისი", "en": "whose", "ru": "чей", "group": "Questions"},
            {"ge": "თერთმეტი", "en": "eleven", "ru": "одиннадцать", "group": "Numbers"},
            {"ge": "თორმეტი", "en": "twelve", "ru": "двенадцать", "group": "Numbers"},
            {"ge": "ოცი", "en": "twenty", "ru": "двадцать", "group": "Numbers"},
            {"ge": "ოცდაათი", "en": "thirty", "ru": "тридцать", "group": "Numbers"},
            {"ge": "ორმოცი", "en": "forty", "ru": "сорок", "group": "Numbers"},
            {"ge": "ასი", "en": "hundred", "ru": "сто", "group": "Numbers"},
            {"ge": "ათასი", "en": "thousand", "ru": "тысяча", "group": "Numbers"},
            {"ge": "წელი", "en": "year", "ru": "год", "group": "Age"},
            {"ge": "წლის", "en": "years old (age)", "ru": "лет (возраст)", "group": "Age"},
            {"ge": "წლის ვარ", "en": "I am … years old", "ru": "мне … лет", "group": "Age"},
        ],
    },
    "6": {
        "title": "Daily Routine + Origin",
        "grammar": {
            "en": "Nationality: country + -ელი (ქართველი). Origin adj: -ური. Time: რამდენია საათი? / X საათია.",
            "ru": "Национальность: страна + -ელი (ქართველი = грузин). Прилаг. происхождения: -ური. Время: «сколько часов?» → რამდენია საათი?",
            "example_ge": "მე ქართველი ვარ. სამი საათია.",
            "example_en": "I am Georgian. It's three o'clock.",
            "bullets": [
                "Country → person: საქართველო → ქართველი, ამერიკა → ამერიკელი",
                "რამდენია საათი? = What time is it?",
                "X საათია = It's X o'clock",
                "ყოველდღე · ხშირად · იშვიათად · არასოდეს",
            ],
        },
        "easier_than_russian": "Days of the week are simpler — no «в понедельник» case changes needed at A1 level.",
        "phrases": [
            {"ge": "მე ქართველი ვარ.", "en": "I am Georgian.", "ru": "Я грузин(ка)."},
            {"ge": "რამდენია საათი?", "en": "What time is it?", "ru": "Сколько часов?"},
            {"ge": "სამი საათია.", "en": "It's three o'clock.", "ru": "Три часа."},
            {"ge": "ყოველდღე ვმუშაობ.", "en": "I work every day.", "ru": "Я работаю каждый день."},
        ],
        "vocab": [
            {"ge": "საქართველო", "en": "Georgia (country)", "ru": "Грузия", "group": "Countries"},
            {"ge": "რუსეთი", "en": "Russia", "ru": "Россия", "group": "Countries"},
            {"ge": "ამერიკა", "en": "America", "ru": "Америка", "group": "Countries"},
            {"ge": "ინგლისი", "en": "England", "ru": "Англия", "group": "Countries"},
            {"ge": "გერმანია", "en": "Germany", "ru": "Германия", "group": "Countries"},
            {"ge": "საფრანგეთი", "en": "France", "ru": "Франция", "group": "Countries"},
            {"ge": "ქართველი", "en": "Georgian (person)", "ru": "грузин", "group": "Nationalities"},
            {"ge": "რუსი", "en": "Russian (person)", "ru": "русский", "group": "Nationalities"},
            {"ge": "ამერიკელი", "en": "American", "ru": "американец", "group": "Nationalities"},
            {"ge": "ინგლისელი", "en": "English (person)", "ru": "англичанин", "group": "Nationalities"},
            {"ge": "გერმანელი", "en": "German", "ru": "немец", "group": "Nationalities"},
            {"ge": "ფრანგი", "en": "French (person)", "ru": "француз", "group": "Nationalities"},
            {"ge": "ეროვნება", "en": "nationality", "ru": "национальность", "group": "Nationalities"},
            {"ge": "ორშაბათი", "en": "Monday", "ru": "понедельник", "group": "Days"},
            {"ge": "სამშაბათი", "en": "Tuesday", "ru": "вторник", "group": "Days"},
            {"ge": "ოთხშაბათი", "en": "Wednesday", "ru": "среда", "group": "Days"},
            {"ge": "ხუთშაბათი", "en": "Thursday", "ru": "четверг", "group": "Days"},
            {"ge": "პარასკევი", "en": "Friday", "ru": "пятница", "group": "Days"},
            {"ge": "შაბათი", "en": "Saturday", "ru": "суббота", "group": "Days"},
            {"ge": "კვირა", "en": "Sunday / week", "ru": "воскресенье / неделя", "group": "Days"},
            {"ge": "იანვარი", "en": "January", "ru": "январь", "group": "Months"},
            {"ge": "თებერვალი", "en": "February", "ru": "февраль", "group": "Months"},
            {"ge": "მარტი", "en": "March", "ru": "март", "group": "Months"},
            {"ge": "აპრილი", "en": "April", "ru": "апрель", "group": "Months"},
            {"ge": "მაისი", "en": "May", "ru": "май", "group": "Months"},
            {"ge": "ივნისი", "en": "June", "ru": "июнь", "group": "Months"},
            {"ge": "ივლისი", "en": "July", "ru": "июль", "group": "Months"},
            {"ge": "აგვისტო", "en": "August", "ru": "август", "group": "Months"},
            {"ge": "სექტემბერი", "en": "September", "ru": "сентябрь", "group": "Months"},
            {"ge": "ოქტომბერი", "en": "October", "ru": "октябрь", "group": "Months"},
            {"ge": "ნოემბერი", "en": "November", "ru": "ноябрь", "group": "Months"},
            {"ge": "დეკემბერი", "en": "December", "ru": "декабрь", "group": "Months"},
            {"ge": "ყოველდღე", "en": "every day", "ru": "каждый день", "group": "Frequency"},
            {"ge": "ხშირად", "en": "often", "ru": "часто", "group": "Frequency"},
            {"ge": "იშვიათად", "en": "rarely", "ru": "редко", "group": "Frequency"},
            {"ge": "არასოდეს", "en": "never", "ru": "никогда", "group": "Frequency"},
            {"ge": "საათი", "en": "hour / o'clock", "ru": "час", "group": "Time"},
            {"ge": "რამდენია საათი", "en": "what time is it?", "ru": "сколько часов?", "group": "Time"},
            {"ge": "დღე", "en": "day", "ru": "день", "group": "Time"},
            {"ge": "თვე", "en": "month", "ru": "месяц", "group": "Time"},
        ],
    },
    "7": {
        "title": "Face, Body, Clothing, Colors",
        "grammar": {
            "en": "Particle ც = also/too — attaches to the END of the word (ლამაზიც = beautiful too). Adjectives come BEFORE the noun.",
            "ru": "Частица ც = «тоже» — ставится ПОСЛЕ слова (не перед, как «тоже» в русском!). Прилагательное ПЕРЕД существительным: ლამაზი სახე = красивое лицо.",
            "example_ge": "ლამაზია და ჭკვიანიც.",
            "example_en": "She's beautiful and smart too.",
            "bullets": [
                "Adjective BEFORE noun: ლამაზი სახე = beautiful face",
                "Particle ც at END = also/too: ლამაზიც = beautiful too",
                "Colors and adjectives don't change for gender in nominative",
            ],
        },
        "easier_than_russian": "Adjectives don't change for gender or case in nominative — ლამაზი works for everyone and everything!",
        "phrases": [
            {"ge": "ლამაზი სახე.", "en": "A beautiful face.", "ru": "Красивое лицо."},
            {"ge": "ეს ქვედაბოლო ვარდისფერია.", "en": "This skirt is pink.", "ru": "Эта юбка розовая."},
            {"ge": "ლამაზია და ჭკვიანიც.", "en": "She's beautiful and smart too.", "ru": "Она красивая и тоже умная."},
            {"ge": "რა ფერია?", "en": "What color is it?", "ru": "Какого цвета?"},
        ],
        "vocab": [
            {"ge": "სახე", "en": "face", "ru": "лицо", "group": "Face & body"},
            {"ge": "თვალი", "en": "eye", "ru": "глаз", "group": "Face & body"},
            {"ge": "ცხვირი", "en": "nose", "ru": "нос", "group": "Face & body"},
            {"ge": "პირი", "en": "mouth", "ru": "рот", "group": "Face & body"},
            {"ge": "ყური", "en": "ear", "ru": "ухо", "group": "Face & body"},
            {"ge": "თმა", "en": "hair", "ru": "волосы", "group": "Face & body"},
            {"ge": "კბილი", "en": "tooth", "ru": "зуб", "group": "Face & body"},
            {"ge": "წარბი", "en": "eyebrow", "ru": "бровь", "group": "Face & body"},
            {"ge": "კისერი", "en": "neck", "ru": "шея", "group": "Face & body"},
            {"ge": "ხელი", "en": "hand / arm", "ru": "рука", "group": "Face & body"},
            {"ge": "ფეხი", "en": "foot / leg", "ru": "нога", "group": "Face & body"},
            {"ge": "ზურგი", "en": "back", "ru": "спина", "group": "Face & body"},
            {"ge": "მუცელი", "en": "belly / stomach", "ru": "живот", "group": "Face & body"},
            {"ge": "ტანსაცმელი", "en": "clothes", "ru": "одежда", "group": "Clothing"},
            {"ge": "ფეხსაცმელი", "en": "shoes", "ru": "обувь", "group": "Clothing"},
            {"ge": "კაბა", "en": "dress", "ru": "платье", "group": "Clothing"},
            {"ge": "ქვედაბოლო", "en": "skirt", "ru": "юбка", "group": "Clothing"},
            {"ge": "პერანგი", "en": "shirt", "ru": "рубашка", "group": "Clothing"},
            {"ge": "თაჯაკი", "en": "jacket / windbreaker", "ru": "куртка / ветровка", "group": "Clothing"},
            {"ge": "შარვალი", "en": "trousers", "ru": "брюки", "group": "Clothing"},
            {"ge": "ქურთუკი", "en": "coat", "ru": "пальто", "group": "Clothing"},
            {"ge": "პიჯაკი", "en": "suit jacket", "ru": "пиджак", "group": "Clothing"},
            {"ge": "ქუნქული", "en": "hat", "ru": "шляпа / шапка", "group": "Clothing"},
            {"ge": "ქურთული", "en": "sock", "ru": "носок", "group": "Clothing"},
            {"ge": "ჩანთა", "en": "bag", "ru": "сумка", "group": "Clothing"},
            {"ge": "ფერი", "en": "color", "ru": "цвет", "group": "Colors"},
            {"ge": "წითელი", "en": "red", "ru": "красный", "group": "Colors"},
            {"ge": "ლურჯი", "en": "blue", "ru": "синий", "group": "Colors"},
            {"ge": "მწვანე", "en": "green", "ru": "зелёный", "group": "Colors"},
            {"ge": "შავი", "en": "black", "ru": "чёрный", "group": "Colors"},
            {"ge": "თეთრი", "en": "white", "ru": "белый", "group": "Colors"},
            {"ge": "ყვითელი", "en": "yellow", "ru": "жёлтый", "group": "Colors"},
            {"ge": "ნარინჯისფერი", "en": "orange", "ru": "оранжевый", "group": "Colors"},
            {"ge": "ვარდისფერი", "en": "pink", "ru": "розовый", "group": "Colors"},
            {"ge": "იისფერი", "en": "purple / violet", "ru": "фиолетовый", "group": "Colors"},
            {"ge": "ყავისფერი", "en": "brown", "ru": "коричневый", "group": "Colors"},
            {"ge": "რუხი", "en": "grey", "ru": "серый", "group": "Colors"},
            {"ge": "ლამაზი", "en": "beautiful", "ru": "красивый", "group": "Adjectives"},
            {"ge": "მაღალი", "en": "tall", "ru": "высокий", "group": "Adjectives"},
            {"ge": "დაბალი", "en": "short (height)", "ru": "низкий", "group": "Adjectives"},
            {"ge": "გრძელი", "en": "long", "ru": "длинный", "group": "Adjectives"},
            {"ge": "მოკლე", "en": "short (length)", "ru": "короткий", "group": "Adjectives"},
            {"ge": "სქელი", "en": "thick", "ru": "толстый", "group": "Adjectives"},
            {"ge": "გამხდარი", "en": "thin / slim", "ru": "худой / тонкий", "group": "Adjectives"},
            {"ge": "ჭკვიანი", "en": "smart", "ru": "умный", "group": "Adjectives"},
        ],
    },
    "8": {
        "title": "Schedule, Seasons, Shopping",
        "grammar": {
            "en": "Motion verbs: მიდის (goes away), მოდის (comes), შედის (enters), გადის (goes out). Superlative: ყველაზე + adj. Date: X რიცხვია.",
            "ru": "Глаголы движения: მიდის (идёт отсюда), მოდის (идёт сюда), შედის (входит), გადის (выходит). Превосходная степень: ყველაზე + прил. Дата: X რიცხვია = «X-е число».",
            "example_ge": "ის მოდის. ყველაზე იაფი.",
            "example_en": "He/she is coming. The cheapest.",
        },
        "easier_than_russian": "Ordinals are regular: მე+number+ე (like «двадцатый» but more predictable).",
        "vocab": [
            {"ge": "გაზაფხული", "en": "spring", "ru": "весна", "group": "Seasons"},
            {"ge": "ზაფხული", "en": "summer", "ru": "лето", "group": "Seasons"},
            {"ge": "შემოდგომა", "en": "autumn", "ru": "осень", "group": "Seasons"},
            {"ge": "ზამთარი", "en": "winter", "ru": "зима", "group": "Seasons"},
            {"ge": "წელიწადი", "en": "season / year cycle", "ru": "время года / год", "group": "Seasons"},
            {"ge": "ფასი", "en": "price", "ru": "цена", "group": "Shopping"},
            {"ge": "ლარი", "en": "lari (GEL)", "ru": "лари", "group": "Shopping"},
            {"ge": "ხურდა", "en": "change (money)", "ru": "сдача", "group": "Shopping"},
            {"ge": "ძვირი", "en": "expensive", "ru": "дорогой", "group": "Shopping"},
            {"ge": "იაფი", "en": "cheap", "ru": "дешёвый", "group": "Shopping"},
            {"ge": "ყველაზე", "en": "the most (superlative)", "ru": "самый", "group": "Shopping"},
            {"ge": "კილოგრამი", "en": "kilogram", "ru": "килограмм", "group": "Shopping"},
            {"ge": "გრამი", "en": "gram", "ru": "грамм", "group": "Shopping"},
            {"ge": "პირველი", "en": "first", "ru": "первый", "group": "Ordinals"},
            {"ge": "მეორე", "en": "second", "ru": "второй", "group": "Ordinals"},
            {"ge": "მესამე", "en": "third", "ru": "третий", "group": "Ordinals"},
            {"ge": "მეოთხე", "en": "fourth", "ru": "четвёртый", "group": "Ordinals"},
            {"ge": "მეხუთე", "en": "fifth", "ru": "пятый", "group": "Ordinals"},
            {"ge": "რიცხვი", "en": "date / number", "ru": "число", "group": "Schedule"},
            {"ge": "მიდის", "en": "goes (away)", "ru": "идёт (отсюда)", "group": "Motion verbs"},
            {"ge": "მოდის", "en": "comes", "ru": "идёт (сюда)", "group": "Motion verbs"},
            {"ge": "შედის", "en": "enters", "ru": "входит", "group": "Motion verbs"},
            {"ge": "გადის", "en": "goes out / crosses", "ru": "выходит / переходит", "group": "Motion verbs"},
        ],
    },
    "9": {
        "title": "Hobbies, Leisure, Nature",
        "grammar": {
            "en": "შემიძლია = I can. მომწონს = I like (lit. 'it pleases me'). Past: წავედი (I went), მოვედი (I came).",
            "ru": "შემიძლია = «я могу». მომწონს = «мне нравится» (дативный подлежащее + глагол!). Прошедшее: წავედი (я ушёл), მოვედი (я пришёл).",
            "example_ge": "შემიძლია კითხვა. მომწონს ფილმი.",
            "example_en": "I can read. I like the film.",
        },
        "easier_than_russian": "No perfective/imperfective pair to choose for წავედი — one past form.",
        "vocab": [
            {"ge": "ფილმი", "en": "film", "ru": "фильм", "group": "Leisure"},
            {"ge": "თეატრი", "en": "theatre", "ru": "театр", "group": "Leisure"},
            {"ge": "მუზეუმი", "en": "museum", "ru": "музей", "group": "Leisure"},
            {"ge": "კონცერტი", "en": "concert", "ru": "концерт", "group": "Leisure"},
            {"ge": "ფესტივალი", "en": "festival", "ru": "фестиваль", "group": "Leisure"},
            {"ge": "სპექტაკლი", "en": "play / show", "ru": "спектакль", "group": "Leisure"},
            {"ge": "კითხვა", "en": "reading", "ru": "чтение", "group": "Hobbies"},
            {"ge": "წერა", "en": "writing", "ru": "письмо / писание", "group": "Hobbies"},
            {"ge": "სიარული", "en": "walking", "ru": "прогулка", "group": "Hobbies"},
            {"ge": "ბაღი", "en": "garden / park", "ru": "сад / парк", "group": "Nature"},
            {"ge": "ტყე", "en": "forest", "ru": "лес", "group": "Nature"},
            {"ge": "ზღვა", "en": "sea", "ru": "море", "group": "Nature"},
            {"ge": "მთა", "en": "mountain", "ru": "гора", "group": "Nature"},
            {"ge": "ტბა", "en": "lake", "ru": "озеро", "group": "Nature"},
            {"ge": "მდინარე", "en": "river", "ru": "река", "group": "Nature"},
            {"ge": "შემიძლია", "en": "I can", "ru": "я могу", "group": "Useful phrases"},
            {"ge": "მომწონს", "en": "I like (it pleases me)", "ru": "мне нравится", "group": "Useful phrases"},
            {"ge": "არ მომწონს", "en": "I don't like", "ru": "мне не нравится", "group": "Useful phrases"},
            {"ge": "წავედი", "en": "I went", "ru": "я ушёл / пошёл", "group": "Past tense"},
            {"ge": "მოვედი", "en": "I came", "ru": "я пришёл", "group": "Past tense"},
        ],
    },
    "10": {
        "title": "City & Transport",
        "grammar": {
            "en": "Locative postpositions: -ში (in), -ზე (on), -თან (near). Transport: instrumental -ით (ავტობუსით = by bus).",
            "ru": "ПОСТПОЗИЦИИ (после слова!): -ში = «в», -ზე = «на», -თან = «у/около». Транспорт: творительный -ით = «на» (ავტობუსით = на автобусе).",
            "example_ge": "სახლში ვარ. ავტობუსით მივდივარ.",
            "example_en": "I am at home. I go by bus.",
        },
        "easier_than_russian": "Postpositions are glued to the word — no separate preposition to memorize separately from case.",
        "vocab": [
            {"ge": "ქუჩა", "en": "street", "ru": "улица", "group": "City"},
            {"ge": "გამზირი", "en": "avenue", "ru": "проспект", "group": "City"},
            {"ge": "მოედანი", "en": "square / plaza", "ru": "площадь", "group": "City"},
            {"ge": "უბანი", "en": "neighborhood / district", "ru": "район", "group": "City"},
            {"ge": "შენობა", "en": "building", "ru": "здание", "group": "City"},
            {"ge": "სახლი", "en": "house / home", "ru": "дом", "group": "City"},
            {"ge": "ბანკი", "en": "bank", "ru": "банк", "group": "City"},
            {"ge": "სადგური", "en": "station", "ru": "станция", "group": "Transport"},
            {"ge": "მეტრო", "en": "metro", "ru": "метро", "group": "Transport"},
            {"ge": "ავტობუსი", "en": "bus", "ru": "автобус", "group": "Transport"},
            {"ge": "ტაქსი", "en": "taxi", "ru": "такси", "group": "Transport"},
            {"ge": "მატარებელი", "en": "train", "ru": "поезд", "group": "Transport"},
            {"ge": "ტრანსპორტი", "en": "transport", "ru": "транспорт", "group": "Transport"},
            {"ge": "ავტობუსით", "en": "by bus", "ru": "на автобусе", "group": "Transport"},
            {"ge": "მეტროთი", "en": "by metro", "ru": "на метро", "group": "Transport"},
            {"ge": "ფეხით", "en": "on foot", "ru": "пешком", "group": "Transport"},
            {"ge": "მარჯვნივ", "en": "to the right", "ru": "направо", "group": "Directions"},
            {"ge": "მარცხნივ", "en": "to the left", "ru": "налево", "group": "Directions"},
            {"ge": "პირდაპირ", "en": "straight ahead", "ru": "прямо", "group": "Directions"},
            {"ge": "ახლოს", "en": "near", "ru": "близко", "group": "Directions"},
            {"ge": "შორს", "en": "far", "ru": "далеко", "group": "Directions"},
        ],
    },
    "11": {
        "title": "Home & Apartment",
        "grammar": {
            "en": "მაქვს = I have (things). მყავს = I have (people/animals). Dative subject — like Russian «у меня есть».",
            "ru": "მაქვს = «у меня есть» (вещь). მყავს = «у меня есть» (человек/животное). Подлежащее в дательном — как «у меня»!",
            "example_ge": "მაქვს ბინა. მყავს კატა.",
            "example_en": "I have an apartment. I have a cat.",
        },
        "easier_than_russian": "Two verbs for 'have' but the rule is simple: things vs. living beings.",
        "vocab": [
            {"ge": "ბინა", "en": "apartment / flat", "ru": "квартира", "group": "Rooms"},
            {"ge": "ოთახი", "en": "room", "ru": "комната", "group": "Rooms"},
            {"ge": "სამზარეულო", "en": "kitchen", "ru": "кухня", "group": "Rooms"},
            {"ge": "საძინებელი", "en": "bedroom", "ru": "спальня", "group": "Rooms"},
            {"ge": "სასადილო", "en": "dining room", "ru": "столовая", "group": "Rooms"},
            {"ge": "აბაზანა", "en": "bathroom", "ru": "ванная", "group": "Rooms"},
            {"ge": "ბალკონი", "en": "balcony", "ru": "балкон", "group": "Rooms"},
            {"ge": "მაგიდა", "en": "table", "ru": "стол", "group": "Furniture"},
            {"ge": "სკამი", "en": "chair", "ru": "стул", "group": "Furniture"},
            {"ge": "სავარძელი", "en": "armchair", "ru": "кресло", "group": "Furniture"},
            {"ge": "საწოლი", "en": "bed", "ru": "кровать", "group": "Furniture"},
            {"ge": "კარადა", "en": "wardrobe / cupboard", "ru": "шкаф", "group": "Furniture"},
            {"ge": "მაცივარი", "en": "fridge", "ru": "холодильник", "group": "Appliances"},
            {"ge": "გაზქურა", "en": "stove / cooker", "ru": "плита", "group": "Appliances"},
            {"ge": "ტელევიზორი", "en": "TV", "ru": "телевизор", "group": "Appliances"},
            {"ge": "მაქვს", "en": "I have (thing)", "ru": "у меня есть (вещь)", "group": "To have"},
            {"ge": "მყავს", "en": "I have (person/animal)", "ru": "у меня есть (живое)", "group": "To have"},
            {"ge": "კატა", "en": "cat", "ru": "кошка", "group": "Living things"},
            {"ge": "ძაღლი", "en": "dog", "ru": "собака", "group": "Living things"},
        ],
    },
    "12": {
        "title": "Review + Letter Writing",
        "grammar": {
            "en": "Past tense review. Duration: X წელია ვსწავლობ = I've been studying for X years. Polite phrases for real conversation.",
            "ru": "Повторение прошедшего времени. Длительность: X წელია ვსწავლობ = «я учу уже X лет». Вежливые фразы для разговора.",
            "example_ge": "ორი წელია ვსწავლობ ქართულს. გმადლობ!",
            "example_en": "I've been studying Georgian for two years. Thank you!",
        },
        "easier_than_russian": "გმადლობ works for thank you — no gendered «спасиба/спасибо» distinction needed.",
        "vocab": [
            {"ge": "წერილი", "en": "letter", "ru": "письмо", "group": "Writing"},
            {"ge": "ელ-ფოსტა", "en": "email", "ru": "электронная почта", "group": "Writing"},
            {"ge": "ბარათი", "en": "card / postcard", "ru": "открытка", "group": "Writing"},
            {"ge": "მისამართი", "en": "address", "ru": "адрес", "group": "Writing"},
            {"ge": "ანკეტა", "en": "form / questionnaire", "ru": "анкета", "group": "Writing"},
            {"ge": "გმადლობ", "en": "thank you", "ru": "спасибо", "group": "Polite phrases"},
            {"ge": "გმადლობთ", "en": "thank you (formal)", "ru": "спасибо (уваж.)", "group": "Polite phrases"},
            {"ge": "არაფრის", "en": "you're welcome", "ru": "не за что", "group": "Polite phrases"},
            {"ge": "უკაცრავად", "en": "excuse me / sorry", "ru": "извините", "group": "Polite phrases"},
            {"ge": "გისმენთ", "en": "hello (on phone)", "ru": "алло / слушаю", "group": "Polite phrases"},
            {"ge": "გთხოვ", "en": "please (informal)", "ru": "пожалуйста", "group": "Polite phrases"},
            {"ge": "გთხოვთ", "en": "please (formal)", "ru": "пожалуйста (уваж.)", "group": "Polite phrases"},
            {"ge": "ვსწავლობ", "en": "I study / I am learning", "ru": "я учу / изучаю", "group": "Review"},
            {"ge": "ვიყავი", "en": "I was", "ru": "я был / была", "group": "Review"},
            {"ge": "მქონდა", "en": "I had (thing)", "ru": "у меня было", "group": "Review"},
            {"ge": "მექნება", "en": "I will have", "ru": "у меня будет", "group": "Review"},
        ],
    },
}


def main():
    with open(LESSON_DATA, encoding="utf-8") as f:
        data = json.load(f)
    data["a1"] = A1
    with open(LESSON_DATA, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    counts = {k: len(v["vocab"]) for k, v in A1.items()}
    print(f"✅ Updated A1 with {len(A1)} lessons in {LESSON_DATA}")
    for k in sorted(counts, key=int):
        print(f"   L{k}: {counts[k]} words — {A1[k]['title']}")


if __name__ == "__main__":
    main()
